# Data Preprocessing

In [1]:
import pandas as pd
import numpy as np
# import Bio
# from Bio.Seq import Seq

pd.set_option("display.max_rows", 60)
pd.set_option("display.max_columns", 100)

import os

## For dataset AFs2_CB_is_baby_HC_is_adult.rds.csv

In [2]:
afx2 = pd.read_csv('../data/input_data/AFs2_CB_is_baby_HC_is_adult.rds.csv')
# add pheno and dataset origin for each record
afx2['pheno'] = 'nopheno'
afx2['dataset'] = 'afs2'
print('dataframe shape:', afx2.shape)
print('records for each donor:\n', afx2['donor'].value_counts())
afx2.head()

dataframe shape: (53319, 15)
records for each donor:
 CB6    9772
CB2    9153
CB7    8643
CB3    7483
CB5    6056
CB4    3941
HC4    3601
HC3    2476
HC5    2194
Name: donor, dtype: int64

,txt,count,freq,cdr3nt,cdr3aa,v,d,j,VEnd,DStart,DEnd,JStart,donor,pheno,dataset
0,CB2h_Vd2.txt,322,0.021503,TGTGCCTGTGACATACTGGGGGACACCGATAAACTCATCTTT,CACDILGDTDKLIF,TRDV2,TRDD3,TRDJ1,12,13,21,22,CB2,nopheno,afs2
1,CB2h_Vd2.txt,245,0.016361,TGTGCCTGTGACAGACTGGGGGAACCGTACACCGATAAACTCATCTTT,CACDRLGEPYTDKLIF,TRDV2,TRDD3,TRDJ1,12,14,22,26,CB2,nopheno,afs2
2,CB2h_Vd2.txt,218,0.014558,TGTGCCTGTGACCCAGTACTGGGGGATACCGGGTACACCGATAAAC...,CACDPVLGDTGYTDKLIF,TRDV2,TRDD3,TRDJ1,11,12,25,26,CB2,nopheno,afs2
3,CB2h_Vd2.txt,184,0.012287,TGTGCCTGTGACGTACTGGGGGACACCGATAAACTCATCTTT,CACDVLGDTDKLIF,TRDV2,TRDD3,TRDJ1,11,12,21,22,CB2,nopheno,afs2
4,CB2h_Vd2.txt,116,0.007746,TGTGCCTGTGACACCTGGGGGAGCTCCTGGGACACCCGACAGATGT...,CACDTWGSSWDTRQMFF,TRDV2,.,TRDJ3,14,-1,-1,19,CB2,nopheno,afs2

In [3]:
# check the unique donor (afx2['donor'].unique()) and the unique txt file (afx2['txt'].unique()), 
# we can know that there are three files for each donor, 
# including the zol_vd2, h_vd2 and unst_vd2, except for donor HC4, it have an extra 'HC4h_190627_Vd2.txt' file.

In [4]:
afx2['donor'].value_counts()

CB6    9772
CB2    9153
CB7    8643
CB3    7483
CB5    6056
CB4    3941
HC4    3601
HC3    2476
HC5    2194
Name: donor, dtype: int64

In [5]:
# define donor_category for each record
afx2['donor_category'] = np.where(afx2['donor'].str.startswith('CB'), 'CB', 'adult')
print('records for each donor_category:\n', afx2['donor_category'].value_counts())
afx2.head()

records for each donor_category:
 CB       45048
adult     8271
Name: donor_category, dtype: int64

,txt,count,freq,cdr3nt,cdr3aa,v,d,j,VEnd,DStart,DEnd,JStart,donor,pheno,dataset,donor_category
0,CB2h_Vd2.txt,322,0.021503,TGTGCCTGTGACATACTGGGGGACACCGATAAACTCATCTTT,CACDILGDTDKLIF,TRDV2,TRDD3,TRDJ1,12,13,21,22,CB2,nopheno,afs2,CB
1,CB2h_Vd2.txt,245,0.016361,TGTGCCTGTGACAGACTGGGGGAACCGTACACCGATAAACTCATCTTT,CACDRLGEPYTDKLIF,TRDV2,TRDD3,TRDJ1,12,14,22,26,CB2,nopheno,afs2,CB
2,CB2h_Vd2.txt,218,0.014558,TGTGCCTGTGACCCAGTACTGGGGGATACCGGGTACACCGATAAAC...,CACDPVLGDTGYTDKLIF,TRDV2,TRDD3,TRDJ1,11,12,25,26,CB2,nopheno,afs2,CB
3,CB2h_Vd2.txt,184,0.012287,TGTGCCTGTGACGTACTGGGGGACACCGATAAACTCATCTTT,CACDVLGDTDKLIF,TRDV2,TRDD3,TRDJ1,11,12,21,22,CB2,nopheno,afs2,CB
4,CB2h_Vd2.txt,116,0.007746,TGTGCCTGTGACACCTGGGGGAGCTCCTGGGACACCCGACAGATGT...,CACDTWGSSWDTRQMFF,TRDV2,.,TRDJ3,14,-1,-1,19,CB2,nopheno,afs2,CB

In [6]:
afx2

,txt,count,freq,cdr3nt,cdr3aa,v,d,j,VEnd,DStart,DEnd,JStart,donor,pheno,dataset,donor_category
0,CB2h_Vd2.txt,322,0.021503,TGTGCCTGTGACATACTGGGGGACACCGATAAACTCATCTTT,CACDILGDTDKLIF,TRDV2,TRDD3,TRDJ1,12,13,21,22,CB2,nopheno,afs2,CB
1,CB2h_Vd2.txt,245,0.016361,TGTGCCTGTGACAGACTGGGGGAACCGTACACCGATAAACTCATCTTT,CACDRLGEPYTDKLIF,TRDV2,TRDD3,TRDJ1,12,14,22,26,CB2,nopheno,afs2,CB
2,CB2h_Vd2.txt,218,0.014558,TGTGCCTGTGACCCAGTACTGGGGGATACCGGGTACACCGATAAAC...,CACDPVLGDTGYTDKLIF,TRDV2,TRDD3,TRDJ1,11,12,25,26,CB2,nopheno,afs2,CB
3,CB2h_Vd2.txt,184,0.012287,TGTGCCTGTGACGTACTGGGGGACACCGATAAACTCATCTTT,CACDVLGDTDKLIF,TRDV2,TRDD3,TRDJ1,11,12,21,22,CB2,nopheno,afs2,CB
4,CB2h_Vd2.txt,116,0.007746,TGTGCCTGTGACACCTGGGGGAGCTCCTGGGACACCCGACAGATGT...,CACDTWGSSWDTRQMFF,TRDV2,.,TRDJ3,14,-1,-1,19,CB2,nopheno,afs2,CB
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
53314,HC5zol_Vd2.txt,1,0.000067,TGTGCCTGCGACACTGTGGGGATCGGAGATAAACTCATCTTT,CACDTVGIGDKLIF,TRDV2,TRDD3,TRDJ1,13,17,22,27,HC5,nopheno,afs2,adult
53315,HC5zol_Vd2.txt,1,0.000067,TGTGCCCGTGACCCCGTACCTGTGGCCGATAAACTCATCTCC,CARDPVPVADKLIS,TRDV2,.,TRDJ1,15,-1,-1,25,HC5,nopheno,afs2,adult
53316,HC5zol_Vd2.txt,1,0.000067,TGTGCCCGCGACACCGTGGGGTCTGGGGACAAGCTCATCTTT,CARDTVGSGDKLIF,TRDV2,TRDD3,TRDJ1,15,22,26,27,HC5,nopheno,afs2,adult
53317,HC5zol_Vd2.txt,1,0.000067,TGTGCCTGTGACCAACTGGGGGATTATAAACTCATCTTC,CACDQLGDYKLIF,TRDV2,TRDD3,TRDJ1,11,14,23,25,HC5,nopheno,afs2,adult
53318,HC5zol_Vd2.txt,1,0.000067,TGTGCCTGTGACACACTGGGTGGCAATAAACTCATCTTT,CACDTLGGNKLIF,TRDV2,TRDD3,TRDJ1,13,14,19,25,HC5,nopheno,afs2,adult

In [7]:
# check the uniqueness of the cdr3nt for each donor
a1 = afx2['donor'].value_counts().rename_axis('unique_donor').reset_index(name='rows_for_donor')

for i in list(a1['unique_donor']):
    print(i, len(afx2[afx2['donor'] == i]['cdr3nt']), len(afx2[afx2['donor'] == i]['cdr3nt'].unique()), afx2[afx2['donor'] == i]['freq'].sum())

CB6 9772 9139 2.9999999999999796
CB2 9153 8659 2.9999999999999747
CB7 8643 8024 2.9999999999999827
CB3 7483 7094 2.9999999999999747
CB5 6056 5695 2.999999999999968
CB4 3941 3747 2.9999999999999756
HC4 3601 2354 3.9999999999999702
HC3 2476 1958 2.999999999999974
HC5 2194 1532 2.9999999999999876

In [8]:
# the sum of the frequency also indicates the number of files accumulated for each donor

In [9]:
afx2['txt'].unique() # only select unst

array(['CB2h_Vd2.txt', 'CB2unst_Vd2.txt', 'CB2zol_Vd2.txt',
       'CB3h_Vd2.txt', 'CB3unst_Vd2.txt', 'CB3zol_Vd2.txt',
       'CB4h_Vd2.txt', 'CB4unst_Vd2.txt', 'CB4zol_Vd2.txt',
       'CB5h_Vd2.txt', 'CB5unst_Vd2.txt', 'CB5zol_Vd2.txt',
       'CB6h_Vd2.txt', 'CB6unst_Vd2.txt', 'CB6zol_Vd2.txt',
       'CB7h_Vd2.txt', 'CB7unst_Vd2.txt', 'CB7zol_Vd2.txt',
       'HC3h_Vd2.txt', 'HC3unst_Vd2.txt', 'HC3zol_Vd2.txt',
       'HC4h_190627_Vd2.txt', 'HC4h_Vd2.txt', 'HC4unst_Vd2.txt',
       'HC4zol_Vd2.txt', 'HC5h_Vd2.txt', 'HC5unst_Vd2.txt',
       'HC5zol_Vd2.txt'], dtype=object)

In [10]:
print(afx2.shape)
afx2_unst = afx2[afx2['txt'].str.contains('unst_')]
print(afx2_unst.shape)

(53319, 16)
(11608, 16)

In [11]:
afx2_donoragg = afx2_unst.copy()

In [12]:
# result indicates there are no duplicate rows concerning all the columns
a2 = afx2[afx2.duplicated()]
a2

Empty DataFrame
Columns: [txt, count, freq, cdr3nt, cdr3aa, v, d, j, VEnd, DStart, DEnd, JStart, donor, pheno, dataset, donor_category]
Index: []

In [13]:
# duplicate rows in dataframe if only consider the two columns
a2 = afx2[afx2.duplicated(['donor', 'cdr3nt'])] 
# indicates donors tested in different conditions/files (stimulate using different reagent) may have same cdr3nt
a2

,txt,count,freq,cdr3nt,cdr3aa,v,d,j,VEnd,DStart,DEnd,JStart,donor,pheno,dataset,donor_category
3634,CB2unst_Vd2.txt,369,0.024646,TGTGCCTGTGACACTGGGGGATACACCGATAAACTCATCTTT,CACDTGGYTDKLIF,TRDV2,.,TRDJ1,16,-1,-1,21,CB2,nopheno,afs2,CB
3635,CB2unst_Vd2.txt,335,0.022375,TGTGCCTGTGACACCGGGGGATACACCGATAAACTCATCTTT,CACDTGGYTDKLIF,TRDV2,.,TRDJ1,16,-1,-1,21,CB2,nopheno,afs2,CB
3636,CB2unst_Vd2.txt,214,0.014293,TGTGCCTGTGACTGGGGGAGCTCCTGGGACACCCGACAGATGTTTTTC,CACDWGSSWDTRQMFF,TRDV2,.,TRDJ3,11,-1,-1,16,CB2,nopheno,afs2,CB
3637,CB2unst_Vd2.txt,214,0.014293,TGTGCCTGTGACATACTGGGGGACACCGATAAACTCATCTTT,CACDILGDTDKLIF,TRDV2,TRDD3,TRDJ1,12,13,21,22,CB2,nopheno,afs2,CB
3638,CB2unst_Vd2.txt,200,0.013358,TGTGCCTGTGACACCTGGGGGAGCTCCTGGGACACCCGACAGATGT...,CACDTWGSSWDTRQMFF,TRDV2,.,TRDJ3,14,-1,-1,19,CB2,nopheno,afs2,CB
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
53267,HC5zol_Vd2.txt,1,0.000067,TGTGCCTGTGACACTCTACTGGGGGATACGACCGATAAACTCATCTTT,CACDTLLGDTTDKLIF,TRDV2,TRDD3,TRDJ1,13,16,25,26,HC5,nopheno,afs2,adult
53274,HC5zol_Vd2.txt,1,0.000067,TGTGCCTGTGACACCGTGGAAAGGGATAACACCGATAAACTCATCTTT,CACDTVERDNTDKLIF,TRDV2,TRDD3,TRDJ1,15,22,27,28,HC5,nopheno,afs2,adult
53291,HC5zol_Vd2.txt,1,0.000067,TGTGCCTGTGACACCGTTGGGGGCCTCGAGGGTAAACTCATCTTT,CACDTVGGLEGKLIF,TRDV2,TRDD2,TRDJ1,18,21,25,32,HC5,nopheno,afs2,adult
53295,HC5zol_Vd2.txt,1,0.000067,TGTGCCTGTGACACCGTGGATCGGTACACCGATAAACTCATCTTT,CACDTVDRYTDKLIF,TRDV2,.,TRDJ1,15,-1,-1,23,HC5,nopheno,afs2,adult
53298,HC5zol_Vd2.txt,1,0.000067,TGTGCCTGTGACAGAGTGGGATACGCTGTCGATAAACTCATCTTT,CACDRVGYAVDKLIF,TRDV2,TRDD3,TRDJ1,12,17,25,29,HC5,nopheno,afs2,adult

In [14]:
# duplicate rows in dataframe if only consider the two columns
a3 = afx2[afx2.duplicated(['donor', 'cdr3nt', 'v', 'd', 'j'])]
a3

,txt,count,freq,cdr3nt,cdr3aa,v,d,j,VEnd,DStart,DEnd,JStart,donor,pheno,dataset,donor_category
3634,CB2unst_Vd2.txt,369,0.024646,TGTGCCTGTGACACTGGGGGATACACCGATAAACTCATCTTT,CACDTGGYTDKLIF,TRDV2,.,TRDJ1,16,-1,-1,21,CB2,nopheno,afs2,CB
3635,CB2unst_Vd2.txt,335,0.022375,TGTGCCTGTGACACCGGGGGATACACCGATAAACTCATCTTT,CACDTGGYTDKLIF,TRDV2,.,TRDJ1,16,-1,-1,21,CB2,nopheno,afs2,CB
3636,CB2unst_Vd2.txt,214,0.014293,TGTGCCTGTGACTGGGGGAGCTCCTGGGACACCCGACAGATGTTTTTC,CACDWGSSWDTRQMFF,TRDV2,.,TRDJ3,11,-1,-1,16,CB2,nopheno,afs2,CB
3637,CB2unst_Vd2.txt,214,0.014293,TGTGCCTGTGACATACTGGGGGACACCGATAAACTCATCTTT,CACDILGDTDKLIF,TRDV2,TRDD3,TRDJ1,12,13,21,22,CB2,nopheno,afs2,CB
3638,CB2unst_Vd2.txt,200,0.013358,TGTGCCTGTGACACCTGGGGGAGCTCCTGGGACACCCGACAGATGT...,CACDTWGSSWDTRQMFF,TRDV2,.,TRDJ3,14,-1,-1,19,CB2,nopheno,afs2,CB
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
53267,HC5zol_Vd2.txt,1,0.000067,TGTGCCTGTGACACTCTACTGGGGGATACGACCGATAAACTCATCTTT,CACDTLLGDTTDKLIF,TRDV2,TRDD3,TRDJ1,13,16,25,26,HC5,nopheno,afs2,adult
53274,HC5zol_Vd2.txt,1,0.000067,TGTGCCTGTGACACCGTGGAAAGGGATAACACCGATAAACTCATCTTT,CACDTVERDNTDKLIF,TRDV2,TRDD3,TRDJ1,15,22,27,28,HC5,nopheno,afs2,adult
53291,HC5zol_Vd2.txt,1,0.000067,TGTGCCTGTGACACCGTTGGGGGCCTCGAGGGTAAACTCATCTTT,CACDTVGGLEGKLIF,TRDV2,TRDD2,TRDJ1,18,21,25,32,HC5,nopheno,afs2,adult
53295,HC5zol_Vd2.txt,1,0.000067,TGTGCCTGTGACACCGTGGATCGGTACACCGATAAACTCATCTTT,CACDTVDRYTDKLIF,TRDV2,.,TRDJ1,15,-1,-1,23,HC5,nopheno,afs2,adult
53298,HC5zol_Vd2.txt,1,0.000067,TGTGCCTGTGACAGAGTGGGATACGCTGTCGATAAACTCATCTTT,CACDRVGYAVDKLIF,TRDV2,TRDD3,TRDJ1,12,17,25,29,HC5,nopheno,afs2,adult

In [15]:
a2 = a2[['donor', 'cdr3nt', 'v', 'd', 'j']]
a3 = a3[['donor', 'cdr3nt', 'v', 'd', 'j']]

In [16]:
a2[~a2.isin(a3)].dropna()

,donor,cdr3nt,v,d,j
39858,CB7,TGTGCCTGTGACCTCGTCGGAACTGGGGCGACAGCACAACTCTTCTTT,TRDV2,TRDD3,TRDJ2

In [17]:
a4 = afx2[(afx2['donor']=='CB7') & (afx2['cdr3nt']=='TGTGCCTGTGACCTCGTCGGAACTGGGGCGACAGCACAACTCTTCTTT')]
a4
# when cdr3nt is the same for a specific donor, ['v', 'd', 'j'] is not necessarily the same

,txt,count,freq,cdr3nt,cdr3aa,v,d,j,VEnd,DStart,DEnd,JStart,donor,pheno,dataset,donor_category
38518,CB7h_Vd2.txt,1,0.000067,TGTGCCTGTGACCTCGTCGGAACTGGGGCGACAGCACAACTCTTCTTT,CACDLVGTGATAQLFF,TRDV2,TRDD3,TRDJ1,11,21,27,37,CB7,nopheno,afs2,CB
39858,CB7unst_Vd2.txt,6,0.000410,TGTGCCTGTGACCTCGTCGGAACTGGGGCGACAGCACAACTCTTCTTT,CACDLVGTGATAQLFF,TRDV2,TRDD3,TRDJ2,11,21,27,29,CB7,nopheno,afs2,CB

In [18]:
# check when ['v', 'd', 'j'] is the same, whether the ['VEnd', 'DStart', 'DEnd', 'JStart'] is the same for the same donor with the same cdr3nt sequence
a5 = afx2[afx2.duplicated(['donor', 'cdr3nt', 'v', 'd', 'j', 'VEnd', 'DStart', 'DEnd', 'JStart'])]
len(a5)

5116

In [19]:
a6 = afx2[afx2.duplicated(['donor', 'cdr3nt', 'VEnd', 'DStart', 'DEnd', 'JStart'])]
len(a6)

5116

In [20]:
# this result indicates in this dataset, when ['v', 'd', 'j'] is the same, the ['VEnd', 'DStart', 'DEnd', 'JStart'] is also the same.
len(a5)==len(a6)

True

In [21]:
a0 = afx2.groupby(['donor', 'cdr3nt'])['cdr3nt'].count().reset_index(name='counts')
print(type(a0))
a0.head()

<class 'pandas.core.frame.DataFrame'>

  donor                                             cdr3nt  counts
0   CB2  AGTGCCTGTGACACCCTACTGGGGGATACGAGGACCGATAAACTCA...       1
1   CB2  AGTGCCTGTGACACCGTATCTCACTGGGGGATTCCTCCTTTGGCAG...       1
2   CB2   AGTGCCTGTGACACCGTTGGGGGATACCCCTCCGATAAACTCATCTTT       1
3   CB2  AGTGCCTGTGACACGTACTGGGGGATACGGCCTGATTCGACAGCAC...       1
4   CB2         ATCCTGGGGGATACTTTTTTTTTGACAGCACAACTCTTCTTT       1

In [22]:
a0['counts'].value_counts()

1    44541
2     2377
3     1112
4      172
Name: counts, dtype: int64

In [23]:
afx2['txt'].unique() # only select unst or combine them without considering the count and freq, only count the unique existence of cdr3nt

array(['CB2h_Vd2.txt', 'CB2unst_Vd2.txt', 'CB2zol_Vd2.txt',
       'CB3h_Vd2.txt', 'CB3unst_Vd2.txt', 'CB3zol_Vd2.txt',
       'CB4h_Vd2.txt', 'CB4unst_Vd2.txt', 'CB4zol_Vd2.txt',
       'CB5h_Vd2.txt', 'CB5unst_Vd2.txt', 'CB5zol_Vd2.txt',
       'CB6h_Vd2.txt', 'CB6unst_Vd2.txt', 'CB6zol_Vd2.txt',
       'CB7h_Vd2.txt', 'CB7unst_Vd2.txt', 'CB7zol_Vd2.txt',
       'HC3h_Vd2.txt', 'HC3unst_Vd2.txt', 'HC3zol_Vd2.txt',
       'HC4h_190627_Vd2.txt', 'HC4h_Vd2.txt', 'HC4unst_Vd2.txt',
       'HC4zol_Vd2.txt', 'HC5h_Vd2.txt', 'HC5unst_Vd2.txt',
       'HC5zol_Vd2.txt'], dtype=object)

In [24]:
afx2.head()

,txt,count,freq,cdr3nt,cdr3aa,v,d,j,VEnd,DStart,DEnd,JStart,donor,pheno,dataset,donor_category
0,CB2h_Vd2.txt,322,0.021503,TGTGCCTGTGACATACTGGGGGACACCGATAAACTCATCTTT,CACDILGDTDKLIF,TRDV2,TRDD3,TRDJ1,12,13,21,22,CB2,nopheno,afs2,CB
1,CB2h_Vd2.txt,245,0.016361,TGTGCCTGTGACAGACTGGGGGAACCGTACACCGATAAACTCATCTTT,CACDRLGEPYTDKLIF,TRDV2,TRDD3,TRDJ1,12,14,22,26,CB2,nopheno,afs2,CB
2,CB2h_Vd2.txt,218,0.014558,TGTGCCTGTGACCCAGTACTGGGGGATACCGGGTACACCGATAAAC...,CACDPVLGDTGYTDKLIF,TRDV2,TRDD3,TRDJ1,11,12,25,26,CB2,nopheno,afs2,CB
3,CB2h_Vd2.txt,184,0.012287,TGTGCCTGTGACGTACTGGGGGACACCGATAAACTCATCTTT,CACDVLGDTDKLIF,TRDV2,TRDD3,TRDJ1,11,12,21,22,CB2,nopheno,afs2,CB
4,CB2h_Vd2.txt,116,0.007746,TGTGCCTGTGACACCTGGGGGAGCTCCTGGGACACCCGACAGATGT...,CACDTWGSSWDTRQMFF,TRDV2,.,TRDJ3,14,-1,-1,19,CB2,nopheno,afs2,CB

#### afx2_copy combine all the unique cdr3nt for each donor without condering the datasource, count and freq

In [25]:
# afx2_copy combine all the unique cdr3nt for each donor without condering the datasource, count and freq
afx2_copy = afx2.copy()
afx2_copy['donor**dataset**category'] = afx2_copy['donor'] + \
    '**' + afx2_copy['dataset'] + '**' + afx2_copy['donor_category']
afx2_copy['donor**dataset**category**pheno'] = afx2_copy['donor'] + '**' + \
    afx2_copy['dataset'] + '**' + \
    afx2_copy['donor_category'] + '**' + afx2_copy['pheno']
print(afx2_copy['donor**dataset**category**pheno'].unique())
print(afx2_copy.columns)
# ignore count, freq and datasource (txt) to get the unique cdr3nt for each donor
print(afx2_copy.shape)

afx2_copy1 = afx2_copy.copy()
afx2_copy1.drop_duplicates(subset=afx2_copy1.columns.tolist(
), keep='first', inplace=True, ignore_index=False)
print(afx2_copy1.shape)

afx2_copy1.drop_duplicates(subset=['freq', 'cdr3nt', 'cdr3aa', 'v', 'd', 'j', 'VEnd',
                                   'DStart', 'DEnd', 'JStart', 'donor**dataset**category'], keep='first', inplace=True, ignore_index=False)
print(afx2_copy1.shape)

afx2_copy.drop_duplicates(subset=['cdr3nt', 'v', 'd', 'j', 'VEnd', 'DStart', 'DEnd', 'JStart',
                                  'donor**dataset**category'], keep='first', inplace=True, ignore_index=False)
print(afx2_copy.shape)
afx2_copy.head()

['CB2**afs2**CB**nopheno' 'CB3**afs2**CB**nopheno'
 'CB4**afs2**CB**nopheno' 'CB5**afs2**CB**nopheno'
 'CB6**afs2**CB**nopheno' 'CB7**afs2**CB**nopheno'
 'HC3**afs2**adult**nopheno' 'HC4**afs2**adult**nopheno'
 'HC5**afs2**adult**nopheno']
Index(['txt', 'count', 'freq', 'cdr3nt', 'cdr3aa', 'v', 'd', 'j', 'VEnd',
       'DStart', 'DEnd', 'JStart', 'donor', 'pheno', 'dataset',
       'donor_category', 'donor**dataset**category',
       'donor**dataset**category**pheno'],
      dtype='object')
(53319, 18)
(53319, 18)
(53319, 18)
(48203, 18)

,txt,count,freq,cdr3nt,cdr3aa,v,d,j,VEnd,DStart,DEnd,JStart,donor,pheno,dataset,donor_category,donor**dataset**category,donor**dataset**category**pheno
0,CB2h_Vd2.txt,322,0.021503,TGTGCCTGTGACATACTGGGGGACACCGATAAACTCATCTTT,CACDILGDTDKLIF,TRDV2,TRDD3,TRDJ1,12,13,21,22,CB2,nopheno,afs2,CB,CB2**afs2**CB,CB2**afs2**CB**nopheno
1,CB2h_Vd2.txt,245,0.016361,TGTGCCTGTGACAGACTGGGGGAACCGTACACCGATAAACTCATCTTT,CACDRLGEPYTDKLIF,TRDV2,TRDD3,TRDJ1,12,14,22,26,CB2,nopheno,afs2,CB,CB2**afs2**CB,CB2**afs2**CB**nopheno
2,CB2h_Vd2.txt,218,0.014558,TGTGCCTGTGACCCAGTACTGGGGGATACCGGGTACACCGATAAAC...,CACDPVLGDTGYTDKLIF,TRDV2,TRDD3,TRDJ1,11,12,25,26,CB2,nopheno,afs2,CB,CB2**afs2**CB,CB2**afs2**CB**nopheno
3,CB2h_Vd2.txt,184,0.012287,TGTGCCTGTGACGTACTGGGGGACACCGATAAACTCATCTTT,CACDVLGDTDKLIF,TRDV2,TRDD3,TRDJ1,11,12,21,22,CB2,nopheno,afs2,CB,CB2**afs2**CB,CB2**afs2**CB**nopheno
4,CB2h_Vd2.txt,116,0.007746,TGTGCCTGTGACACCTGGGGGAGCTCCTGGGACACCCGACAGATGT...,CACDTWGSSWDTRQMFF,TRDV2,.,TRDJ3,14,-1,-1,19,CB2,nopheno,afs2,CB,CB2**afs2**CB,CB2**afs2**CB**nopheno

In [26]:
afx2_copyx = afx2_copy1[['txt', 'cdr3nt', 'cdr3aa', 'v', 'd', 'j', 'VEnd',
                  'DStart', 'DEnd', 'JStart', 'donor**dataset**category']]
duplicate=afx2_copyx[afx2_copyx.duplicated()]
duplicate

Empty DataFrame
Columns: [txt, cdr3nt, cdr3aa, v, d, j, VEnd, DStart, DEnd, JStart, donor**dataset**category]
Index: []

In [27]:
afx2_copy['donor'].value_counts()

CB6    9139
CB2    8659
CB7    8025
CB3    7094
CB5    5695
CB4    3747
HC4    2354
HC3    1958
HC5    1532
Name: donor, dtype: int64

## For dataset adult_16.rds.csv

In [28]:
a16 = pd.read_csv('../data/input_data/adult_16.rds.csv')
a16['pheno'] = 'nopheno'
a16['donor_category'] = 'adult'
a16['dataset'] = 'a16'
a16['donor'] = a16['donor'].apply(lambda x: x.split('.')[1])
print('dataframe shape:', a16.shape)
print('records for each donor:\n', a16['donor'].value_counts())
a16.head()

dataframe shape: (14702, 16)
records for each donor:
 SA62       3182
SA61       1863
SA71       1746
1553A      1596
H1614A2    1347
1537B       881
1563        872
1542        791
SA70        686
SA65        489
H1610       396
1564        333
H1603       260
1540A       121
1410         89
H1601        50
Name: donor, dtype: int64

,txt,count,freq,cdr3nt,cdr3aa,v,d,j,VEnd,DStart,DEnd,JStart,donor,pheno,donor_category,dataset
0,VDJTOOLS_.1410-A-PE_S24_L001_R1_001.fastq_XCR.txt,2563,0.332728,TGTGCCTGTGACTCTTTAGGGGGGGGGATACTCGACCCCGATAAAC...,CDSLGGGILDPDKLIF,TRDV2,TRDD3,TRDJ1,11,22,33,34,1410,nopheno,adult,a16
1,VDJTOOLS_.1410-A-PE_S24_L001_R1_001.fastq_XCR.txt,641,0.083214,TGTGCCTGTGACGCCCTCGCTGGGGGATCGTACACCGATAAACTCA...,CDALAGGSYTDKLIF,TRDV2,TRDD3,TRDJ1,14,19,27,29,1410,nopheno,adult,a16
2,VDJTOOLS_.1410-A-PE_S24_L001_R1_001.fastq_XCR.txt,359,0.046605,TGTGCCTGTGACACCGTCTTTAGCGGGGGGATACGCGACGATAAAC...,CDTVFSGGIRDDKLIF,TRDV2,TRDD3,TRDJ1,15,25,36,38,1410,nopheno,adult,a16
3,VDJTOOLS_.1410-A-PE_S24_L001_R1_001.fastq_XCR.txt,351,0.045567,TGTGCCTGTGACACCGTGACAGTACTGGGGGATAACTCCTGGGACA...,CDTVTVLGDNSWDTRQMFF,TRDV2,TRDD3,TRDJ3,15,19,33,35,1410,nopheno,adult,a16
4,VDJTOOLS_.1410-A-PE_S24_L001_R1_001.fastq_XCR.txt,284,0.036869,TGTGCCTGTGACCCGATCGGGGGAGAGGACACCGATAAACTCATCTTT,CDPIGGEDTDKLIF,TRDV2,TRDD3,TRDJ1,14,18,23,28,1410,nopheno,adult,a16

In [29]:
# check the uniqueness of the cdr3nt for each donor

a1 = a16['donor'].value_counts().rename_axis('unique_donor').reset_index(name='rows_for_donor')

for i in list(a1['unique_donor']):
    print(i, len(a16[a16['donor'] == i]['cdr3nt']), len(a16[a16['donor'] == i]['cdr3nt'].unique()), a16[a16['donor'] == i]['freq'].sum())
    
# the following result shows for each donor, the cdr3nt sequence is unique

SA62 3182 3182 0.9999999999999933
SA61 1863 1863 0.999999999999993
SA71 1746 1746 0.999999999999992
1553A 1596 1596 0.9999999999999921
H1614A2 1347 1347 0.999999999999995
1537B 881 881 0.9999999999999918
1563 872 872 0.99999999999999
1542 791 791 0.9999999999999916
SA70 686 686 0.999999999999992
SA65 489 489 0.9999999999999952
H1610 396 396 0.9999999999999888
1564 333 333 0.9999999999999947
H1603 260 260 0.999999999999995
1540A 121 121 0.9999999999999976
1410 89 89 0.9999999999999974
H1601 50 50 0.9999999999999986

In [30]:
a0 = a16.groupby(['donor', 'cdr3nt'])['cdr3nt'].count().reset_index(name='counts')
print(type(a0))
a0.head()

<class 'pandas.core.frame.DataFrame'>

  donor                                             cdr3nt  counts
0  1410   TGCGCCCGTGACCCGATCGGGGGAGAGGACACCGATAAACTCATCTTT       1
1  1410  TGTGCCCGTGACACCTTTCCTACTGGGGGACAGGGCTCCTGGGACA...       1
2  1410  TGTGCCCGTGACACGTTACTGGGGGAACCGTACACCAATAAACTCA...       1
3  1410  TGTGCCCGTGACCCCTTACTGGGGGATAGAAATGTCGCGCCTTACA...       1
4  1410      TGTGCCTACGCCGTACTGGGGGATACGGATCATAAACTCATCTTT       1

In [31]:
a0['counts'].value_counts()

1    14702
Name: counts, dtype: int64

#### a16_copy combine all the unique cdr3nt for each donor without condering the datasource, count, freq and pheno

In [32]:
#### a16_copy combine all the unique cdr3nt for each donor without condering the datasource, count, freq and pheno
a16_copy = a16.copy()
a16_copy['donor**dataset**category'] = a16_copy['donor'] + '**' + a16_copy['dataset'] + '**' + a16_copy['donor_category']
a16_copy['donor**dataset**category**pheno'] = a16_copy['donor'] + '**' + a16_copy['dataset'] + '**' + a16_copy['donor_category'] + '**' + a16_copy['pheno']  
print(a16_copy['donor**dataset**category**pheno'].unique())
print(a16_copy.columns)
# ignore count, freq and datasource (txt) to get the unique cdr3nt for each donor
print(a16_copy.shape)
a16_copy.drop_duplicates(subset=['cdr3nt', 'v', 'd', 'j', 'VEnd', 'DStart', 'DEnd', 'JStart',
                                  'donor**dataset**category'], keep='first', inplace=True, ignore_index=False)
print(a16_copy.shape)
a16_copy.head()

['1410**a16**adult**nopheno' '1537B**a16**adult**nopheno'
 '1540A**a16**adult**nopheno' '1542**a16**adult**nopheno'
 '1553A**a16**adult**nopheno' '1563**a16**adult**nopheno'
 '1564**a16**adult**nopheno' 'H1601**a16**adult**nopheno'
 'H1603**a16**adult**nopheno' 'H1610**a16**adult**nopheno'
 'H1614A2**a16**adult**nopheno' 'SA61**a16**adult**nopheno'
 'SA62**a16**adult**nopheno' 'SA65**a16**adult**nopheno'
 'SA70**a16**adult**nopheno' 'SA71**a16**adult**nopheno']
Index(['txt', 'count', 'freq', 'cdr3nt', 'cdr3aa', 'v', 'd', 'j', 'VEnd',
       'DStart', 'DEnd', 'JStart', 'donor', 'pheno', 'donor_category',
       'dataset', 'donor**dataset**category',
       'donor**dataset**category**pheno'],
      dtype='object')
(14702, 18)
(14702, 18)

,txt,count,freq,cdr3nt,cdr3aa,v,d,j,VEnd,DStart,DEnd,JStart,donor,pheno,donor_category,dataset,donor**dataset**category,donor**dataset**category**pheno
0,VDJTOOLS_.1410-A-PE_S24_L001_R1_001.fastq_XCR.txt,2563,0.332728,TGTGCCTGTGACTCTTTAGGGGGGGGGATACTCGACCCCGATAAAC...,CDSLGGGILDPDKLIF,TRDV2,TRDD3,TRDJ1,11,22,33,34,1410,nopheno,adult,a16,1410**a16**adult,1410**a16**adult**nopheno
1,VDJTOOLS_.1410-A-PE_S24_L001_R1_001.fastq_XCR.txt,641,0.083214,TGTGCCTGTGACGCCCTCGCTGGGGGATCGTACACCGATAAACTCA...,CDALAGGSYTDKLIF,TRDV2,TRDD3,TRDJ1,14,19,27,29,1410,nopheno,adult,a16,1410**a16**adult,1410**a16**adult**nopheno
2,VDJTOOLS_.1410-A-PE_S24_L001_R1_001.fastq_XCR.txt,359,0.046605,TGTGCCTGTGACACCGTCTTTAGCGGGGGGATACGCGACGATAAAC...,CDTVFSGGIRDDKLIF,TRDV2,TRDD3,TRDJ1,15,25,36,38,1410,nopheno,adult,a16,1410**a16**adult,1410**a16**adult**nopheno
3,VDJTOOLS_.1410-A-PE_S24_L001_R1_001.fastq_XCR.txt,351,0.045567,TGTGCCTGTGACACCGTGACAGTACTGGGGGATAACTCCTGGGACA...,CDTVTVLGDNSWDTRQMFF,TRDV2,TRDD3,TRDJ3,15,19,33,35,1410,nopheno,adult,a16,1410**a16**adult,1410**a16**adult**nopheno
4,VDJTOOLS_.1410-A-PE_S24_L001_R1_001.fastq_XCR.txt,284,0.036869,TGTGCCTGTGACCCGATCGGGGGAGAGGACACCGATAAACTCATCTTT,CDPIGGEDTDKLIF,TRDV2,TRDD3,TRDJ1,14,18,23,28,1410,nopheno,adult,a16,1410**a16**adult,1410**a16**adult**nopheno

In [33]:
a16_donoragg = a16.copy()

## For dataset babies_55.rds.csv

In [34]:
b55 = pd.read_csv('../data/input_data/babies_55.rds.csv')
b55['pheno'] = 'nopheno'
b55['donor_category'] = 'infant'
b55['dataset'] = 'b55'
print('dataframe shape:', b55.shape)
print('records for each donor:\n', b55['donor'].value_counts())
b55.head()

dataframe shape: (282709, 16)
records for each donor:
 PAX03     18664
PAX19     13680
LT1294    13083
PK28      12420
PK27      12379
PAX14     11709
PK30      11297
LT781     10789
LT304      9706
PAX22      9415
PAX20      9158
PK3        8994
PAX07      7901
PAX05      7309
PK29       7078
PK14       6834
PK16       6584
PAX18      6320
PAX17      6235
LT1268     6012
PAX01      5845
LT801      5761
PAX06      5310
PAX21      4954
PK20       4926
PK10       4873
LT581      4564
PK15       4495
PK8        4421
LT469      3957
PK26       3362
PAX09      3141
PAX10      3037
PAX11      2880
PK22       2573
LT1142     2422
PAX08      2134
PK23       1768
PK5        1748
LT937      1717
PK31       1633
PK32       1576
LT711      1320
PK7        1223
PK4        1094
PK19       1061
PK17       1051
PK24        825
LT915       824
LT1165      630
PAX04       537
PK11        504
PK2         445
PK21        395
PK1         136
Name: donor, dtype: int64

,txt,count,freq,cdr3nt,cdr3aa,v,d,j,VEnd,DStart,DEnd,JStart,donor,pheno,donor_category,dataset
0,VDJTOOLS_.LT1142-150518-Pool_S33_L001_R1_001.f...,558,0.011436,TGTGCCTGTGACGTCTTGGGGGATACGAACGCCGATAAACTCATCTTT,CACDVLGDTNADKLIF,TRDV2,TRDD3,TRDJ1,11,16,26,28,LT1142,nopheno,infant,b55
1,VDJTOOLS_.LT1142-150518-Pool_S33_L001_R1_001.f...,430,0.008813,TGTGCCTGTGACCAACTGGGGGAAGACACCGATAAACTCATCTTT,CACDQLGEDTDKLIF,TRDV2,TRDD3,TRDJ1,11,14,22,25,LT1142,nopheno,infant,b55
2,VDJTOOLS_.LT1142-150518-Pool_S33_L001_R1_001.f...,399,0.008177,TGTGCCTGTGACACCGTGGGGGCCTCGGGAGAACAACTCTTCTTT,CACDTVGASGEQLFF,TRDV2,TRDD3,TRDJ2,15,16,21,29,LT1142,nopheno,infant,b55
3,VDJTOOLS_.LT1142-150518-Pool_S33_L001_R1_001.f...,262,0.005370,TGTGCCTGTGACACAATAGGGGGCCACACGGCTTTGACAGCACAAC...,CACDTIGGHTALTAQLFF,TRDV2,TRDD1,TRDJ2,13,14,18,30,LT1142,nopheno,infant,b55
4,VDJTOOLS_.LT1142-150518-Pool_S33_L001_R1_001.f...,247,0.005062,TGTGCTCTTGGGGAACTGGGCCTTCCTACACTTTACTGGGGGACCT...,CALGELGLPTLYWGTCKLIF,TRDV1,TRDD2,TRDJ1,16,18,28,47,LT1142,nopheno,infant,b55

In [35]:
# check the uniqueness of the cdr3nt for each donor

a1 = b55['donor'].value_counts().rename_axis('unique_donor').reset_index(name='rows_for_donor')
print(len(a1))

for i in list(a1['unique_donor']):
    print(i, len(b55[b55['donor'] == i]['cdr3nt']), len(b55[b55['donor'] == i]['cdr3nt'].unique()), b55[b55['donor'] == i]['freq'].sum())
    
# the following result shows that not all the cdr3nt sequence is unique for each donor

55
PAX03 18664 18664 0.9999999999999979
PAX19 13680 13680 0.9999999999999968
LT1294 13083 13083 0.9999999999999978
PK28 12420 12071 2.9999999999999734
PK27 12379 12379 0.9999999999999947
PAX14 11709 11709 0.9999999999999977
PK30 11297 10829 1.9999999999999867
LT781 10789 10789 0.9999999999999966
LT304 9706 9706 1.0000000000000193
PAX22 9415 9415 0.9999999999999952
PAX20 9158 9158 0.9999999999999973
PK3 8994 8994 0.9999999999999953
PAX07 7901 7901 0.9999999999999971
PAX05 7309 7309 0.9999999999999951
PK29 7078 6916 1.9999999999999805
PK14 6834 6607 1.9999999999999818
PK16 6584 6572 1.9999999999999842
PAX18 6320 6320 0.9999999999999969
PAX17 6235 6235 0.9999999999999917
LT1268 6012 6012 0.9999999999999951
PAX01 5845 5845 0.9999999999999942
LT801 5761 5761 0.9999999999999936
PAX06 5310 5310 0.9999999999999977
PAX21 4954 4954 0.9999999999999968
PK20 4926 4799 1.999999999999976
PK10 4873 4873 0.9999999999999948
LT581 4564 4564 1.0000000000000169
PK15 4495 4495 0.9999999999999933
PK8 4421 4421 0.999999999999994
LT469 3957 3957 0.9999999999999944
PK26 3362 3306 1.9999999999999754
PAX09 3141 3141 0.999999999999993
PAX10 3037 3037 0.9999999999999927
PAX11 2880 2880 0.9999999999999916
PK22 2573 2573 0.99999999999999
LT1142 2422 2422 0.9999999999999865
PAX08 2134 2134 0.9999999999999877
PK23 1768 1768 0.9999999999999825
PK5 1748 1748 0.9999999999999867
LT937 1717 1717 0.9999999999999829
PK31 1633 1633 0.9999999999999848
PK32 1576 1576 0.9999999999999849
LT711 1320 1320 0.9999999999999855
PK7 1223 1223 0.9999999999999892
PK4 1094 1094 0.9999999999999848
PK19 1061 1061 0.9999999999999869
PK17 1051 1040 1.9999999999999738
PK24 825 825 0.9999999999999882
LT915 824 824 0.9999999999999887
LT1165 630 630 0.9999999999999856
PAX04 537 537 0.9999999999999898
PK11 504 504 0.9999999999999868
PK2 445 445 0.9999999999999946
PK21 395 395 0.9999999999999919
PK1 136 136 0.9999999999999972

In [36]:
b55['txt'].unique()

array(['VDJTOOLS_.LT1142-150518-Pool_S33_L001_R1_001.fastq_XCR.txt',
       'VDJTOOLS_.LT1165-pooled-TRD_S56_L001_R1_001.fastq_XCR.txt',
       'VDJTOOLS_.LT1268-18-195-0802-pooled-TRD_S55_L001_R1_001.fastq_XCR.txt',
       'VDJTOOLS_.LT1294-300518-Pool_S36_L001_R1_001.fastq_XCR.txt',
       'VDJTOOLS_.LT304-300518-Pool_S27_L001_R1_001.fastq_XCR.txt',
       'VDJTOOLS_.LT469-18-33-0401-pooled-TRD_S54_L001_R1_001.fastq_XCR.txt',
       'VDJTOOLS_.LT581-030518-Pool_S30_L001_R1_001.fastq_XCR.txt',
       'VDJTOOLS_.LT711-totald_S78_L001_R1_001.fastq_XCR.txt',
       'VDJTOOLS_.LT781-TRD_S15_L001_R1_001.fastq_XCR.txt',
       'VDJTOOLS_.LT801_0602-pooled-TRD_S57_L001_R1_001.fastq_XCR.txt',
       'VDJTOOLS_.LT915_X-pooled-TRD_S70_L001_R1_001.fastq_XCR.txt',
       'VDJTOOLS_.LT937-pooled-TRD_S53_L001_R1_001.fastq_XCR.txt',
       'VDJTOOLS_.Pax01_1_SA39_S39_L001_R1_001.fastq_XCR.txt',
       'VDJTOOLS_.Pax03_0_SA19_S19_L001_R1_001.fastq_XCR.txt',
       'VDJTOOLS_.Pax04_0_SA41_S41_L001_R1_001.fastq_XCR.txt',
       'VDJTOOLS_.Pax05_0_SA35_S35_L001_R1_001.fastq_XCR.txt',
       'VDJTOOLS_.Pax06_0_SA44_S44_L001_R1_001.fastq_XCR.txt',
       'VDJTOOLS_.Pax07_0_SA30_S30_L001_R1_001.fastq_XCR.txt',
       'VDJTOOLS_.Pax08_0_SA10_S10_L001_R1_001.fastq_XCR.txt',
       'VDJTOOLS_.Pax09_0_SA43_S43_L001_R1_001.fastq_XCR.txt',
       'VDJTOOLS_.Pax10_0_SA26_S26_L001_R1_001.fastq_XCR.txt',
       'VDJTOOLS_.Pax11_0_SA49_S49_L001_R1_001.fastq_XCR.txt',
       'VDJTOOLS_.Pax14_6_E8_S79_L001_R1_001.fastq_XCR.txt',
       'VDJTOOLS_.Pax17_0_G9_S75_L001_R1_001.fastq_XCR.txt',
       'VDJTOOLS_.Pax18_0_E10_S80_L001_R1_001.fastq_XCR.txt',
       'VDJTOOLS_.Pax19_0_H10_S88_L001_R1_001.fastq_XCR.txt',
       'VDJTOOLS_.Pax20_0_E11_S81_L001_R1_001.fastq_XCR.txt',
       'VDJTOOLS_.Pax21_0_B12_S67_L001_R1_001.fastq_XCR.txt',
       'VDJTOOLS_.Pax22_0_G12_S78_L001_R1_001.fastq_XCR.txt',
       'w1_d0_PK14a_F_TRD_prev9_190627.txt',
       'w1_d0_PK21a_F_TRD_190815.txt', 'w1_d0_PK24a_F_TRD_191008.txt',
       'w1_d4_PK17a_F_TRD_190815.txt', 'w1_d5_PK23a_F_TRD_191008.txt',
       'w1_d5_PK26a_M_TRD_191008.txt', 'w1_d5_PK31a_M_TRD_191008.txt',
       'w1_d5_PK32a_M_TRD_191008.txt', 'w1_d6_PK16a_M_TRD_190815.txt',
       'w1_d7_PK7a_F_TRD_prev5_190523.txt',
       'w2_d13_PK29a_M_TRD_191008.txt', 'w2_d14_PK28a_F_TRD_191008.txt',
       'w2_d9_PK20a_F_TRD_190815.txt', 'w3_d21_PK28ab_F_TRD_191008.txt',
       'w3_d21_PK30ab_M_TRD_191008.txt', 'w4_d22_PK26b_M_TRD_191008.txt',
       'w4_d22_PK5a_M_TRD_prev8_190523.txt',
       'w4_d28_PK3b_F_TRD_prev2_190523.txt',
       'w4_d28_PK4b_F_TRD_prev7_190523.txt',
       'w5_d29_PK19b_M_TRD_191008.txt',
       'w5_d29_PK1b_M_TRD_prev1_190523.txt',
       'w5_d29_PK20b_F_TRD_191008.txt', 'w5_d29_PK22b_F_TRD_191008.txt',
       'w5_d29_PK2b_F_TRD_prev6_190523.txt',
       'w5_d29_PK8b_M_TRD_prev4b_190523.txt',
       'w5_d30_PK14b_F_TRD_prev12_retest_190815.txt',
       'w5_d30_PK15b_M_TRD_190815.txt', 'w5_d30_PK16b_M_TRD_191008.txt',
       'w5_d31_PK10b_F_TRD_prev10_190627.txt',
       'w5_d31_PK11b_M_TRD_prev11_190627.txt',
       'w5_d32_PK17b_F_TRD_191008.txt', 'w5_d33_PK28b_F_TRD_191008.txt',
       'w5_d33_PK29b_M_TRD_191008.txt', 'w5_d33_PK30b_M_TRD_191008.txt',
       'w5_d35_PK27b_M_TRD_191008.txt'], dtype=object)

In [37]:
len(b55['txt'].unique())
# there are 9 donors that have more than one file, 55 unique donor, 64 txt files

64

In [38]:
print(b55.columns)
print(b55.shape)

Index(['txt', 'count', 'freq', 'cdr3nt', 'cdr3aa', 'v', 'd', 'j', 'VEnd',
       'DStart', 'DEnd', 'JStart', 'donor', 'pheno', 'donor_category',
       'dataset'],
      dtype='object')
(282709, 16)

In [39]:
b55_donoragg = b55.groupby(['cdr3nt', 'cdr3aa', 'v', 'd', 'j',
                            'VEnd', 'DStart', 'DEnd', 'JStart', 
                            'donor', 'donor_category', 'dataset'], as_index=False).agg(
    txt=('txt', lambda x: '/'.join(x)),
    count=('count', sum),
    pheno=('pheno', lambda x: '/'.join(x))
    )
b55_donoragg['freq'] = b55_donoragg.groupby(by='donor')['count'].apply(lambda x: x / x.sum())
b55_donoragg = b55_donoragg.reindex(columns=['txt', 'count', 'freq', 'cdr3nt', 'cdr3aa', 'v', 'd', 'j', 'VEnd', 'DStart', 'DEnd', 'JStart', 'donor', 'pheno', 'donor_category', 'dataset'])

print(b55_donoragg.shape)
b55_donoragg.head()

(281297, 16)

,txt,count,freq,cdr3nt,cdr3aa,v,d,j,VEnd,DStart,DEnd,JStart,donor,pheno,donor_category,dataset
0,VDJTOOLS_.Pax22_0_G12_S78_L001_R1_001.fastq_XC...,1,0.000012,AACGGGCGAAACTGGGGGGCCTACACCGATAAACTCATCTTT,NGRNWGAYTDKLIF,TRDV2,TRDD3,TRDJ1,-1,10,17,21,PAX22,nopheno,infant,b55
1,VDJTOOLS_.Pax03_0_SA19_S19_L001_R1_001.fastq_X...,3,0.000027,AACGGGGGCCCGGGGTACACCGATAAACTCATCTTT,NGGPGYTDKLIF,TRDV1,TRDD3,TRDJ1,-1,3,7,10,PAX03,nopheno,infant,b55
2,VDJTOOLS_.Pax20_0_E11_S81_L001_R1_001.fastq_XC...,50,0.000233,AAGTACTGGGGGATGCCCACCGATAAACTCATCTTT,KYWGMPTDKLIF,TRDV2,TRDD3,TRDJ1,-1,1,13,17,PAX20,nopheno,infant,b55
3,w1_d5_PK32a_M_TRD_191008.txt,1,0.000010,AATGCCTTTGGGTCGTTTGGATTGGGCTCCTGGGACACCCGACAGA...,NAFGSFGLGSWDTRQMFF,TRDV3,.,TRDJ3,8,-1,-1,25,PK32,nopheno,infant,b55
4,VDJTOOLS_.Pax22_0_G12_S78_L001_R1_001.fastq_XC...,18,0.000209,ACCCTGGGATACAACACCGATAAACTCATCTTT,TLGYNTDKLIF,TRDV2,TRDD3,TRDJ1,-1,5,11,13,PAX22,nopheno,infant,b55

In [40]:
b55_donoragg['txt'].value_counts()

VDJTOOLS_.Pax03_0_SA19_S19_L001_R1_001.fastq_XCR.txt            18664
VDJTOOLS_.Pax19_0_H10_S88_L001_R1_001.fastq_XCR.txt             13680
VDJTOOLS_.LT1294-300518-Pool_S36_L001_R1_001.fastq_XCR.txt      13083
w5_d35_PK27b_M_TRD_191008.txt                                   12379
VDJTOOLS_.Pax14_6_E8_S79_L001_R1_001.fastq_XCR.txt              11709
                                                                ...
w1_d5_PK26a_M_TRD_191008.txt/w4_d22_PK26b_M_TRD_191008.txt         56
w2_d14_PK28a_F_TRD_191008.txt/w5_d33_PK28b_F_TRD_191008.txt        33
w2_d14_PK28a_F_TRD_191008.txt/w3_d21_PK28ab_F_TRD_191008.txt       22
w1_d6_PK16a_M_TRD_190815.txt/w5_d30_PK16b_M_TRD_191008.txt         12
w1_d4_PK17a_F_TRD_190815.txt/w5_d32_PK17b_F_TRD_191008.txt         11
Name: txt, Length: 75, dtype: int64

In [41]:
a0 = b55.groupby(['donor', 'cdr3nt'])['cdr3nt'].count().reset_index(name='counts')
print(type(a0))
a0.head()

<class 'pandas.core.frame.DataFrame'>

    donor                                             cdr3nt  counts
0  LT1142   AGTGCCTGTGACACACTGGGGGATACATACACCGATAAACTCATCTTT       1
1  LT1142      AGTGCCTGTGACACCGTGGCCGGGGGATTGGGGAAACTCATCTTT       1
2  LT1142  AGTGCCTGTGACACCGTGGGTGTACTGGGGGCCTACACCGATAAAC...       1
3  LT1142      CGTGCCCGTGACATTTGGGGGATACAGCCCGATAAACTCATCTTT       1
4  LT1142      CGTGCCTGCGACGTACTGGGGGATACCCCCGATAAACTCATCTTT       1

In [42]:
a0['counts'].value_counts()

1    279952
2      1278
3        67
Name: counts, dtype: int64

#### b55_copy combine all the unique cdr3nt for each donor without condering the datasource, count, freq and pheno

In [43]:
#### b55_copy combine all the unique cdr3nt for each donor without condering the datasource, count, freq and pheno
b55_copy = b55.copy()
b55_copy['donor**dataset**category'] = b55_copy['donor'] + '**' + b55_copy['dataset'] + '**' + b55_copy['donor_category']
b55_copy['donor**dataset**category**pheno'] = b55_copy['donor'] + '**' + b55_copy['dataset'] + '**' + b55_copy['donor_category'] + '**' + b55_copy['pheno']  
print(b55_copy['donor**dataset**category**pheno'].unique())
print(b55_copy.columns)
# ignore count, freq and datasource (txt) to get the unique cdr3nt for each donor
print(b55_copy.shape)
b55_copy.drop_duplicates(subset=['cdr3nt', 'v', 'd', 'j', 'VEnd', 'DStart', 'DEnd', 'JStart',
                                 'donor**dataset**category'], keep='first', inplace=True, ignore_index=False)
print(b55_copy.shape)
b55_copy.head()

['LT1142**b55**infant**nopheno' 'LT1165**b55**infant**nopheno'
 'LT1268**b55**infant**nopheno' 'LT1294**b55**infant**nopheno'
 'LT304**b55**infant**nopheno' 'LT469**b55**infant**nopheno'
 'LT581**b55**infant**nopheno' 'LT711**b55**infant**nopheno'
 'LT781**b55**infant**nopheno' 'LT801**b55**infant**nopheno'
 'LT915**b55**infant**nopheno' 'LT937**b55**infant**nopheno'
 'PAX01**b55**infant**nopheno' 'PAX03**b55**infant**nopheno'
 'PAX04**b55**infant**nopheno' 'PAX05**b55**infant**nopheno'
 'PAX06**b55**infant**nopheno' 'PAX07**b55**infant**nopheno'
 'PAX08**b55**infant**nopheno' 'PAX09**b55**infant**nopheno'
 'PAX10**b55**infant**nopheno' 'PAX11**b55**infant**nopheno'
 'PAX14**b55**infant**nopheno' 'PAX17**b55**infant**nopheno'
 'PAX18**b55**infant**nopheno' 'PAX19**b55**infant**nopheno'
 'PAX20**b55**infant**nopheno' 'PAX21**b55**infant**nopheno'
 'PAX22**b55**infant**nopheno' 'PK14**b55**infant**nopheno'
 'PK21**b55**infant**nopheno' 'PK24**b55**infant**nopheno'
 'PK17**b55**infant**nopheno' 'PK23**b55**infant**nopheno'
 'PK26**b55**infant**nopheno' 'PK31**b55**infant**nopheno'
 'PK32**b55**infant**nopheno' 'PK16**b55**infant**nopheno'
 'PK7**b55**infant**nopheno' 'PK29**b55**infant**nopheno'
 'PK28**b55**infant**nopheno' 'PK20**b55**infant**nopheno'
 'PK30**b55**infant**nopheno' 'PK5**b55**infant**nopheno'
 'PK3**b55**infant**nopheno' 'PK4**b55**infant**nopheno'
 'PK19**b55**infant**nopheno' 'PK1**b55**infant**nopheno'
 'PK22**b55**infant**nopheno' 'PK2**b55**infant**nopheno'
 'PK8**b55**infant**nopheno' 'PK15**b55**infant**nopheno'
 'PK10**b55**infant**nopheno' 'PK11**b55**infant**nopheno'
 'PK27**b55**infant**nopheno']
Index(['txt', 'count', 'freq', 'cdr3nt', 'cdr3aa', 'v', 'd', 'j', 'VEnd',
       'DStart', 'DEnd', 'JStart', 'donor', 'pheno', 'donor_category',
       'dataset', 'donor**dataset**category',
       'donor**dataset**category**pheno'],
      dtype='object')
(282709, 18)
(281297, 18)

,txt,count,freq,cdr3nt,cdr3aa,v,d,j,VEnd,DStart,DEnd,JStart,donor,pheno,donor_category,dataset,donor**dataset**category,donor**dataset**category**pheno
0,VDJTOOLS_.LT1142-150518-Pool_S33_L001_R1_001.f...,558,0.011436,TGTGCCTGTGACGTCTTGGGGGATACGAACGCCGATAAACTCATCTTT,CACDVLGDTNADKLIF,TRDV2,TRDD3,TRDJ1,11,16,26,28,LT1142,nopheno,infant,b55,LT1142**b55**infant,LT1142**b55**infant**nopheno
1,VDJTOOLS_.LT1142-150518-Pool_S33_L001_R1_001.f...,430,0.008813,TGTGCCTGTGACCAACTGGGGGAAGACACCGATAAACTCATCTTT,CACDQLGEDTDKLIF,TRDV2,TRDD3,TRDJ1,11,14,22,25,LT1142,nopheno,infant,b55,LT1142**b55**infant,LT1142**b55**infant**nopheno
2,VDJTOOLS_.LT1142-150518-Pool_S33_L001_R1_001.f...,399,0.008177,TGTGCCTGTGACACCGTGGGGGCCTCGGGAGAACAACTCTTCTTT,CACDTVGASGEQLFF,TRDV2,TRDD3,TRDJ2,15,16,21,29,LT1142,nopheno,infant,b55,LT1142**b55**infant,LT1142**b55**infant**nopheno
3,VDJTOOLS_.LT1142-150518-Pool_S33_L001_R1_001.f...,262,0.005370,TGTGCCTGTGACACAATAGGGGGCCACACGGCTTTGACAGCACAAC...,CACDTIGGHTALTAQLFF,TRDV2,TRDD1,TRDJ2,13,14,18,30,LT1142,nopheno,infant,b55,LT1142**b55**infant,LT1142**b55**infant**nopheno
4,VDJTOOLS_.LT1142-150518-Pool_S33_L001_R1_001.f...,247,0.005062,TGTGCTCTTGGGGAACTGGGCCTTCCTACACTTTACTGGGGGACCT...,CALGELGLPTLYWGTCKLIF,TRDV1,TRDD2,TRDJ1,16,18,28,47,LT1142,nopheno,infant,b55,LT1142**b55**infant,LT1142**b55**infant**nopheno

## For dataset bulk_4_adult_donor.rds.csv

In [44]:
b4 = pd.read_csv('../data/input_data/bulk_4_adult_donor.rds.csv')
b4['donor_category'] = 'adult'
b4['dataset'] = 'b4'
print('dataframe shape:', b4.shape)
print('records for each donor:\n', b4['donor'].value_counts())
b4.head()

dataframe shape: (26298, 16)
records for each donor:
 HC13    13521
HC8      6240
HC7      4464
HC3      2073
Name: donor, dtype: int64

,count,freq,cdr3nt,cdr3aa,v,d,j,VEnd,DStart,DEnd,JStart,file,pheno,donor,donor_category,dataset
0,349,0.012277,TGTGCCTGTGACACCGGATTCCTACGAGGGATACCGAACACCGATA...,CACDTGFLRGIPNTDKLIF,TRDV2,TRDD2,TRDJ1,16,18,28,37,VDJTOOLS_.gd17-HC13-260820-TCRD_S4_L001_R1_001...,gdNKT3,HC13,adult,b4
1,290,0.010202,TGTGCCTGTGACACCCTCTCCACAAAACCCGATACTGGGGGTCCCC...,CACDTLSTKPDTGGPPVAYTDKLIF,TRDV2,TRDD3,TRDJ1,14,32,40,53,VDJTOOLS_.gd17-HC13-260820-TCRD_S4_L001_R1_001...,gdNKT3,HC13,adult,b4
2,253,0.008900,TGTGCCTGTGACACCGTACGCATTCCTACTGGGGGATACCCACCTG...,CACDTVRIPTGGYPPAGKLIF,TRDV2,TRDD3,TRDJ1,15,26,38,46,VDJTOOLS_.gd17-HC13-260820-TCRD_S4_L001_R1_001...,gdNKT3,HC13,adult,b4
3,230,0.008091,TGTGCCTGTGACACCGGTTCTCTGGGGTCAGGGGAGTACACCGATA...,CACDTGSLGSGEYTDKLIF,TRDV2,TRDD3,TRDJ1,17,21,26,32,VDJTOOLS_.gd17-HC13-260820-TCRD_S4_L001_R1_001...,gdNKT3,HC13,adult,b4
4,225,0.007915,TGTGCCTGTGACAGCTTACTGGGGGACAAGTACACCGATAAACTCA...,CACDSLLGDKYTDKLIF,TRDV2,TRDD3,TRDJ1,12,16,25,29,VDJTOOLS_.gd17-HC13-260820-TCRD_S4_L001_R1_001...,gdNKT3,HC13,adult,b4

In [45]:
# rename column to be the same as the former three dataset
b4.rename(columns={'file': 'txt'}, inplace=True)

In [46]:
# arrange the sequence of columns to be the same as the former three dataset
b4.columns

Index(['count', 'freq', 'cdr3nt', 'cdr3aa', 'v', 'd', 'j', 'VEnd', 'DStart',
       'DEnd', 'JStart', 'txt', 'pheno', 'donor', 'donor_category', 'dataset'],
      dtype='object')

In [47]:
b4 = b4.reindex(columns=['txt', 'count', 'freq', 'cdr3nt', 'cdr3aa', 'v', 'd', 'j', 'VEnd', 'DStart', 'DEnd', 'JStart', 'donor', 'pheno', 'donor_category', 'dataset'])

In [48]:
b4.columns

Index(['txt', 'count', 'freq', 'cdr3nt', 'cdr3aa', 'v', 'd', 'j', 'VEnd',
       'DStart', 'DEnd', 'JStart', 'donor', 'pheno', 'donor_category',
       'dataset'],
      dtype='object')

In [49]:
a1 = b4['donor'].value_counts().rename_axis('unique_donor').reset_index(name='rows_for_donor')

for i in list(a1['unique_donor']):
    print(i, len(b4[b4['donor'] == i]['cdr3nt']), len(b4[b4['donor'] == i]['cdr3nt'].unique()), b4[b4['donor'] == i]['freq'].sum())

HC13 13521 11329 3.912361389983217
HC8 6240 5254 3.9441651156319604
HC7 4464 3646 3.9584016752634708
HC3 2073 1804 3.961158536623824

In [50]:
print(b4.shape)
b4_donoragg = b4.groupby(['cdr3nt', 'cdr3aa', 'v', 'd', 'j',
                            'VEnd', 'DStart', 'DEnd', 'JStart', 
                            'donor', 'donor_category', 'dataset'], as_index=False).agg(
    txt=('txt', lambda x: '/'.join(x)),
    count=('count', sum),
    pheno=('pheno', lambda x: '/'.join(x))
    )
b4_donoragg['freq'] = b4_donoragg.groupby(by='donor')['count'].apply(lambda x: x / x.sum())
b4_donoragg = b4_donoragg.reindex(columns=['txt', 'count', 'freq', 'cdr3nt', 'cdr3aa', 'v', 'd', 'j', 'VEnd', 'DStart', 'DEnd', 'JStart', 'donor', 'pheno', 'donor_category', 'dataset'])

print(b4_donoragg.shape)
b4_donoragg.head()

(26298, 16)
(22033, 16)

,txt,count,freq,cdr3nt,cdr3aa,v,d,j,VEnd,DStart,DEnd,JStart,donor,pheno,donor_category,dataset
0,VDJTOOLS_.gdCTL1-HC3-260820-TCRD_S5_L001_R1_00...,1,0.000009,AACACTACTGGGGGATACGCAGGACTCATCTTT,NTTGGYAGLIF,TRDV2,TRDD3,TRDJ1,-1,2,19,23,HC3,gdNKT1eff,adult,b4
1,VDJTOOLS_.gdCTL3-HC3-260820-TCRD_S13_L001_R1_0...,1,0.000009,AGTGCCCGTGACGCTATACTGGGGGATACGCGGGACACCGATAAAC...,SARDAILGDTRDTDKLIF,TRDV2,TRDD3,TRDJ1,11,16,31,34,HC3,gdNKT1mem1,adult,b4
2,VDJTOOLS_.gdCTL3-HC8-260820-TCRD_S15_L001_R1_0...,1,0.000009,AGTGCCTGCAGTGACGTCGCGACTGGGGGATACCGTGATAAACTCA...,SACSDVATGGYRDKLIF,TRDV2,TRDD3,TRDJ1,7,21,35,36,HC8,gdNKT1mem1,adult,b4
3,VDJTOOLS_.gdCTL3-HC13-260820-TCRD_S16_L001_R1_...,2,0.000017,AGTGCCTGCGACACGGTTGGCGCGAGGGGAACCGATAAACTCATCTTT,SACDTVGARGTDKLIF,TRDV2,TRDD3,TRDJ1,16,25,29,30,HC13,gdNKT1mem1,adult,b4
4,VDJTOOLS_.gdCTL2-HC8-260820-TCRD_S11_L001_R1_0...,1,0.000009,AGTGCCTGCGACGTACTGGGGGAAACCAATAAACTCATCTTT,SACDVLGETNKLIF,TRDV2,TRDD3,TRDJ1,11,12,22,24,HC8,gdNKT1mem2,adult,b4

In [51]:
# b4_donoragg['pheno'].value_counts()

In [52]:
a0 = b4.groupby(['donor', 'cdr3nt'])['cdr3nt'].count().reset_index(name='counts')
print(type(a0))
a0.head()

<class 'pandas.core.frame.DataFrame'>

  donor                                             cdr3nt  counts
0  HC13   AGTGCCTGCGACACGGTTGGCGCGAGGGGAACCGATAAACTCATCTTT       1
1  HC13  AGTGCCTGTGACAACCTGGGGGATACGCGGTTGACAGCACAACTCT...       1
2  HC13   AGTGCCTGTGACACCCCCTGGGGGACCAACACCGATAAACTCATCCTT       1
3  HC13  AGTGCCTGTGACACCCTAACTGGGGGACCGGAACCTGATAAACTCA...       1
4  HC13  AGTGCCTGTGACACCCTTCCTACTGAGCACTGGGGGACCGGACATC...       1

In [53]:
a0['counts'].value_counts()

1    18596
2     2644
3      758
4       35
Name: counts, dtype: int64

In [54]:
b4['txt'].unique()

array(['VDJTOOLS_.gd17-HC13-260820-TCRD_S4_L001_R1_001.fastq_XCR.txt',
       'VDJTOOLS_.gd17-HC3-260820-TCRD_S1_L001_R1_001.fastq_XCR.txt',
       'VDJTOOLS_.gd17-HC7-260820-TCRD_S2_L001_R1_001.fastq_XCR.txt',
       'VDJTOOLS_.gd17-HC8-260820-TCRD_S3_L001_R1_001.fastq_XCR.txt',
       'VDJTOOLS_.gdCTL1-HC13-260820-TCRD_S8_L001_R1_001.fastq_XCR.txt',
       'VDJTOOLS_.gdCTL1-HC3-260820-TCRD_S5_L001_R1_001.fastq_XCR.txt',
       'VDJTOOLS_.gdCTL1-HC7-260820-TCRD_S6_L001_R1_001.fastq_XCR.txt',
       'VDJTOOLS_.gdCTL1-HC8-260820-TCRD_S7_L001_R1_001.fastq_XCR.txt',
       'VDJTOOLS_.gdCTL2-HC13-260820-TCRD_S12_L001_R1_001.fastq_XCR.txt',
       'VDJTOOLS_.gdCTL2-HC3-260820-TCRD_S9_L001_R1_001.fastq_XCR.txt',
       'VDJTOOLS_.gdCTL2-HC7-260820-TCRD_S10_L001_R1_001.fastq_XCR.txt',
       'VDJTOOLS_.gdCTL2-HC8-260820-TCRD_S11_L001_R1_001.fastq_XCR.txt',
       'VDJTOOLS_.gdCTL3-HC13-260820-TCRD_S16_L001_R1_001.fastq_XCR.txt',
       'VDJTOOLS_.gdCTL3-HC3-260820-TCRD_S13_L001_R1_001.fastq_XCR.txt',
       'VDJTOOLS_.gdCTL3-HC7-260820-TCRD_S14_L001_R1_001.fastq_XCR.txt',
       'VDJTOOLS_.gdCTL3-HC8-260820-TCRD_S15_L001_R1_001.fastq_XCR.txt'],
      dtype=object)

In [55]:
b4['v'].unique()

array(['TRDV2', 'TRAV29/DV5', 'TRDV3', 'TRDV1'], dtype=object)

#### b4_copy combine all the unique cdr3nt for each donor without condering the datasource, count, freq and pheno

In [56]:
#### b4_copy combine all the unique cdr3nt for each donor without condering the datasource, count, freq and pheno
b4_copy = b4.copy()
b4_copy['donor**dataset**category'] = b4_copy['donor'] + '**' + b4_copy['dataset'] + '**' + b4_copy['donor_category']
b4_copy['donor**dataset**category**pheno'] = b4_copy['donor'] + '**' + b4_copy['dataset'] + '**' + b4_copy['donor_category'] + '**' + b4_copy['pheno']  
print(b4_copy['donor**dataset**category**pheno'].unique())
print(b4_copy.columns)
# ignore count, freq and datasource (txt) to get the unique cdr3nt for each donor
print(b4_copy.shape)
b4_copy.drop_duplicates(subset=['cdr3nt', 'v', 'd', 'j', 'VEnd', 'DStart', 'DEnd', 'JStart',
                                  'donor**dataset**category'], keep='first', inplace=True, ignore_index=False)
print(b4_copy.shape)
b4_copy.head()

['HC13**b4**adult**gdNKT3' 'HC3**b4**adult**gdNKT3'
 'HC7**b4**adult**gdNKT3' 'HC8**b4**adult**gdNKT3'
 'HC13**b4**adult**gdNKT1eff' 'HC3**b4**adult**gdNKT1eff'
 'HC7**b4**adult**gdNKT1eff' 'HC8**b4**adult**gdNKT1eff'
 'HC13**b4**adult**gdNKT1mem2' 'HC3**b4**adult**gdNKT1mem2'
 'HC7**b4**adult**gdNKT1mem2' 'HC8**b4**adult**gdNKT1mem2'
 'HC13**b4**adult**gdNKT1mem1' 'HC3**b4**adult**gdNKT1mem1'
 'HC7**b4**adult**gdNKT1mem1' 'HC8**b4**adult**gdNKT1mem1']
Index(['txt', 'count', 'freq', 'cdr3nt', 'cdr3aa', 'v', 'd', 'j', 'VEnd',
       'DStart', 'DEnd', 'JStart', 'donor', 'pheno', 'donor_category',
       'dataset', 'donor**dataset**category',
       'donor**dataset**category**pheno'],
      dtype='object')
(26298, 18)
(22033, 18)

,txt,count,freq,cdr3nt,cdr3aa,v,d,j,VEnd,DStart,DEnd,JStart,donor,pheno,donor_category,dataset,donor**dataset**category,donor**dataset**category**pheno
0,VDJTOOLS_.gd17-HC13-260820-TCRD_S4_L001_R1_001...,349,0.012277,TGTGCCTGTGACACCGGATTCCTACGAGGGATACCGAACACCGATA...,CACDTGFLRGIPNTDKLIF,TRDV2,TRDD2,TRDJ1,16,18,28,37,HC13,gdNKT3,adult,b4,HC13**b4**adult,HC13**b4**adult**gdNKT3
1,VDJTOOLS_.gd17-HC13-260820-TCRD_S4_L001_R1_001...,290,0.010202,TGTGCCTGTGACACCCTCTCCACAAAACCCGATACTGGGGGTCCCC...,CACDTLSTKPDTGGPPVAYTDKLIF,TRDV2,TRDD3,TRDJ1,14,32,40,53,HC13,gdNKT3,adult,b4,HC13**b4**adult,HC13**b4**adult**gdNKT3
2,VDJTOOLS_.gd17-HC13-260820-TCRD_S4_L001_R1_001...,253,0.008900,TGTGCCTGTGACACCGTACGCATTCCTACTGGGGGATACCCACCTG...,CACDTVRIPTGGYPPAGKLIF,TRDV2,TRDD3,TRDJ1,15,26,38,46,HC13,gdNKT3,adult,b4,HC13**b4**adult,HC13**b4**adult**gdNKT3
3,VDJTOOLS_.gd17-HC13-260820-TCRD_S4_L001_R1_001...,230,0.008091,TGTGCCTGTGACACCGGTTCTCTGGGGTCAGGGGAGTACACCGATA...,CACDTGSLGSGEYTDKLIF,TRDV2,TRDD3,TRDJ1,17,21,26,32,HC13,gdNKT3,adult,b4,HC13**b4**adult,HC13**b4**adult**gdNKT3
4,VDJTOOLS_.gd17-HC13-260820-TCRD_S4_L001_R1_001...,225,0.007915,TGTGCCTGTGACAGCTTACTGGGGGACAAGTACACCGATAAACTCA...,CACDSLLGDKYTDKLIF,TRDV2,TRDD3,TRDJ1,12,16,25,29,HC13,gdNKT3,adult,b4,HC13**b4**adult,HC13**b4**adult**gdNKT3

## For the newly added data

In [57]:
datadir = '../data/input_data/new_data/'
print(len(os.listdir(datadir)))
os.listdir(datadir)

8

['VDJTOOLS_.CB2002-day0.txt',
 'VDJTOOLS_.HC9-day0.txt',
 'VDJTOOLS_.CB2005-day0.txt',
 'VDJTOOLS_.HC10-day0.txt',
 'VDJTOOLS_.CB2010-day0.txt',
 'VDJTOOLS_.HC15-day0.txt',
 'VDJTOOLS_.CB2004-day0.txt',
 'VDJTOOLS_.CB2006-day0.txt']

In [58]:
tcrsti = pd.DataFrame()

files = os.listdir(datadir)
print(len(files))

for file in files:
    try:
        filename=file.split('_.')[1]
        donor=filename.split('-')[0]
        sti=filename.split('-')[1].split('.')[0]
        file_tsv = pd.read_csv(os.path.join(datadir,file), sep='\t')
        file_tsv['filename'] = filename
        file_tsv['donor'] = donor
        file_tsv['sti'] = sti
        tcrsti = tcrsti.append(file_tsv)
    except:
        print(file)
        
print(tcrsti.columns)
print(tcrsti.shape)
tcrsti.head()

8
Index(['count', 'freq', 'cdr3nt', 'cdr3aa', 'v', 'd', 'j', 'VEnd', 'DStart',
       'DEnd', 'JStart', 'filename', 'donor', 'sti'],
      dtype='object')
(25110, 14)

,count,freq,cdr3nt,cdr3aa,v,d,j,VEnd,DStart,DEnd,JStart,filename,donor,sti
0,1408,0.020014,TGTGCCTGTGACACCTGGGGGAGCTCCTGGGACACCCGACAGATGT...,CACDTWGSSWDTRQMFF,TRDV2,.,TRDJ3,14,-1,-1,19,CB2002-day0.txt,CB2002,day0
1,1273,0.018095,TGTGCCTGTGACATACTGGGGGACACCGATAAACTCATCTTT,CACDILGDTDKLIF,TRDV2,TRDD3,TRDJ1,12,13,21,22,CB2002-day0.txt,CB2002,day0
2,701,0.009964,TGTGCCTGTGACACCTGGGGGATGACAGCACAACTCTTCTTT,CACDTWGMTAQLFF,TRDV2,TRDD3,TRDJ2,14,15,21,22,CB2002-day0.txt,CB2002,day0
3,655,0.009310,TGTGCCTGTGACGTACTGGGGGACACCGATAAACTCATCTTT,CACDVLGDTDKLIF,TRDV2,TRDD3,TRDJ1,11,12,21,22,CB2002-day0.txt,CB2002,day0
4,628,0.008927,TGTGCCTGTGACATACTGGGGGATACCGATAAACTCATCTTT,CACDILGDTDKLIF,TRDV2,TRDD3,TRDJ1,12,13,23,24,CB2002-day0.txt,CB2002,day0

In [59]:
tcrsti['pheno'] = 'nopheno'
tcrsti['dataset'] = '3sti'
tcrsti['donor_category'] = np.where(tcrsti['donor'].str.startswith('CB'), 'infant', 'adult')
tcrsti.rename(columns={'filename': 'txt'}, inplace=True)
tcrsti = tcrsti[['txt', 'count', 'freq', 'cdr3nt', 'cdr3aa', 'v', 'd', 'j', 'VEnd', 'DStart', 'DEnd', 'JStart', 'donor', 'pheno', 'donor_category', 'dataset']]

In [60]:
# no duplicates
a2 = tcrsti[tcrsti.duplicated()]
a2

Empty DataFrame
Columns: [txt, count, freq, cdr3nt, cdr3aa, v, d, j, VEnd, DStart, DEnd, JStart, donor, pheno, donor_category, dataset]
Index: []

In [61]:
print(tcrsti.shape)
tcrsti_donoragg = tcrsti.groupby(['cdr3nt', 'cdr3aa', 'v', 'd', 'j',
                            'VEnd', 'DStart', 'DEnd', 'JStart', 
                            'donor', 'donor_category', 'dataset'], as_index=False).agg(
    txt=('txt', lambda x: '/'.join(x)),
    count=('count', sum),
    pheno=('pheno', lambda x: '/'.join(x))
    )
tcrsti_donoragg['freq'] = tcrsti_donoragg.groupby(by='donor')['count'].apply(lambda x: x / x.sum())
tcrsti_donoragg = tcrsti_donoragg.reindex(columns=['txt', 'count', 'freq', 'cdr3nt', 'cdr3aa', 'v', 'd', 'j', 'VEnd', 'DStart', 'DEnd', 'JStart', 'donor', 'pheno', 'donor_category', 'dataset'])

print(tcrsti_donoragg.shape)
tcrsti_donoragg.head()

(25110, 16)
(25110, 16)

,txt,count,freq,cdr3nt,cdr3aa,v,d,j,VEnd,DStart,DEnd,JStart,donor,pheno,donor_category,dataset
0,CB2004-day0.txt,16,0.000187,ACCGGAAGACTTCCCGGGGGAACTTTGACAGCACAACTCTTCTTT,TGRLPGGTLTAQLFF,TRDV2,TRDD3,TRDJ2,-1,15,20,22,CB2004,nopheno,infant,3sti
1,CB2004-day0.txt,1,0.000012,ACCGGAAGACTTCCCGGGGGGACTTTGACAGCACAACTCTTCTTT,TGRLPGGTLTAQLFF,TRDV2,TRDD3,TRDJ2,-1,16,21,22,CB2004,nopheno,infant,3sti
2,HC15-day0.txt,1,0.000015,AGTGCCTGCCACCCACTGGGCCTGGGGATACGTTCGCCCACCGATA...,SACHPLGLGIRSPTDKLIF,TRDV2,TRDD3,TRDJ1,7,23,31,38,HC15,nopheno,adult,3sti
3,HC15-day0.txt,1,0.000015,AGTGCCTGCGACACAGGATCAGTGGGGGCCACCGATAAACTCATCTTT,SACDTGSVGATDKLIF,TRDV2,TRDD3,TRDJ1,16,22,27,29,HC15,nopheno,adult,3sti
4,HC15-day0.txt,1,0.000015,AGTGCCTGCGACACATGGGGTACTGGGAGTATCCCGGTTAATAAAC...,SACDTWGTGSIPVNKLIF,TRDV2,TRDD3,TRDJ1,13,19,26,40,HC15,nopheno,adult,3sti

## Merge the five datasets

In [62]:
afx2_donoragg.shape, b4_donoragg.shape, b55_donoragg.shape, a16_donoragg.shape, tcrsti_donoragg.shape

((11608, 16), (22033, 16), (281297, 16), (14702, 16), (25110, 16))

In [63]:
m5d_donoragg = pd.concat([afx2_donoragg, b4_donoragg, b55_donoragg, a16_donoragg, tcrsti_donoragg])
print(m5d_donoragg.shape)
print(m5d_donoragg.columns)
from Bio.Seq import Seq
m5d_donoragg['cdr3nt_seq'] = m5d_donoragg['cdr3nt'].apply(lambda x: Seq(x))
m5d_donoragg['cdr3aa_translated'] = m5d_donoragg['cdr3nt_seq'].apply(lambda x:Seq(x).translate())
m5d_donoragg['cdr3aa_string'] = m5d_donoragg['cdr3aa_translated'].apply(lambda x: str(x))
m5d_donoragg['aastring_length'] = m5d_donoragg['cdr3aa_string'].apply(lambda x: len(x))
m5d_donoragg['donor_category3'] = np.where(m5d_donoragg['donor'].str.contains('CB'), 'CB', m5d_donoragg.donor_category)
m5d_donoragg['unique_donor'] = m5d_donoragg['donor'] + '**' + m5d_donoragg['dataset']

print(m5d_donoragg.columns)
m5d_donoragg.head()

(354750, 16)
Index(['txt', 'count', 'freq', 'cdr3nt', 'cdr3aa', 'v', 'd', 'j', 'VEnd',
       'DStart', 'DEnd', 'JStart', 'donor', 'pheno', 'dataset',
       'donor_category'],
      dtype='object')
Index(['txt', 'count', 'freq', 'cdr3nt', 'cdr3aa', 'v', 'd', 'j', 'VEnd',
       'DStart', 'DEnd', 'JStart', 'donor', 'pheno', 'dataset',
       'donor_category', 'cdr3nt_seq', 'cdr3aa_translated', 'cdr3aa_string',
       'aastring_length', 'donor_category3', 'unique_donor'],
      dtype='object')

,txt,count,freq,cdr3nt,cdr3aa,v,d,j,VEnd,DStart,DEnd,JStart,donor,pheno,dataset,donor_category,cdr3nt_seq,cdr3aa_translated,cdr3aa_string,aastring_length,donor_category3,unique_donor
3634,CB2unst_Vd2.txt,369,0.024646,TGTGCCTGTGACACTGGGGGATACACCGATAAACTCATCTTT,CACDTGGYTDKLIF,TRDV2,.,TRDJ1,16,-1,-1,21,CB2,nopheno,afs2,CB,"(T, G, T, G, C, C, T, G, T, G, A, C, A, C, T, ...","(C, A, C, D, T, G, G, Y, T, D, K, L, I, F)",CACDTGGYTDKLIF,14,CB,CB2**afs2
3635,CB2unst_Vd2.txt,335,0.022375,TGTGCCTGTGACACCGGGGGATACACCGATAAACTCATCTTT,CACDTGGYTDKLIF,TRDV2,.,TRDJ1,16,-1,-1,21,CB2,nopheno,afs2,CB,"(T, G, T, G, C, C, T, G, T, G, A, C, A, C, C, ...","(C, A, C, D, T, G, G, Y, T, D, K, L, I, F)",CACDTGGYTDKLIF,14,CB,CB2**afs2
3636,CB2unst_Vd2.txt,214,0.014293,TGTGCCTGTGACTGGGGGAGCTCCTGGGACACCCGACAGATGTTTTTC,CACDWGSSWDTRQMFF,TRDV2,.,TRDJ3,11,-1,-1,16,CB2,nopheno,afs2,CB,"(T, G, T, G, C, C, T, G, T, G, A, C, T, G, G, ...","(C, A, C, D, W, G, S, S, W, D, T, R, Q, M, F, F)",CACDWGSSWDTRQMFF,16,CB,CB2**afs2
3637,CB2unst_Vd2.txt,214,0.014293,TGTGCCTGTGACATACTGGGGGACACCGATAAACTCATCTTT,CACDILGDTDKLIF,TRDV2,TRDD3,TRDJ1,12,13,21,22,CB2,nopheno,afs2,CB,"(T, G, T, G, C, C, T, G, T, G, A, C, A, T, A, ...","(C, A, C, D, I, L, G, D, T, D, K, L, I, F)",CACDILGDTDKLIF,14,CB,CB2**afs2
3638,CB2unst_Vd2.txt,200,0.013358,TGTGCCTGTGACACCTGGGGGAGCTCCTGGGACACCCGACAGATGT...,CACDTWGSSWDTRQMFF,TRDV2,.,TRDJ3,14,-1,-1,19,CB2,nopheno,afs2,CB,"(T, G, T, G, C, C, T, G, T, G, A, C, A, C, C, ...","(C, A, C, D, T, W, G, S, S, W, D, T, R, Q, M, ...",CACDTWGSSWDTRQMFF,17,CB,CB2**afs2

In [64]:
## Remove one of the duplicated donors
# afs2**HC3 == b4**HC3, afs2**HC4 == a16**SA70, b4**HC4 == a16**SA65
m5d_donoragg.unique_donor.unique()

array(['CB2**afs2', 'CB3**afs2', 'CB4**afs2', 'CB5**afs2', 'CB6**afs2',
       'CB7**afs2', 'HC3**afs2', 'HC4**afs2', 'HC5**afs2', 'HC3**b4',
       'HC8**b4', 'HC13**b4', 'HC7**b4', 'PAX22**b55', 'PAX03**b55',
       'PAX20**b55', 'PK32**b55', 'PK10**b55', 'PK3**b55', 'PK27**b55',
       'LT304**b55', 'PAX19**b55', 'LT781**b55', 'PK15**b55',
       'PAX07**b55', 'PK24**b55', 'PAX14**b55', 'PAX11**b55', 'PK26**b55',
       'PK29**b55', 'PK16**b55', 'PAX10**b55', 'PK5**b55', 'PK7**b55',
       'PK2**b55', 'PK22**b55', 'PAX09**b55', 'LT469**b55', 'LT1294**b55',
       'PK28**b55', 'LT1268**b55', 'LT581**b55', 'LT1142**b55',
       'PK20**b55', 'PK30**b55', 'PK21**b55', 'PAX21**b55', 'LT937**b55',
       'PK4**b55', 'PAX01**b55', 'PK1**b55', 'LT711**b55', 'PAX06**b55',
       'PAX18**b55', 'PK19**b55', 'PK14**b55', 'PAX05**b55', 'PAX04**b55',
       'LT801**b55', 'PAX08**b55', 'PK8**b55', 'PK23**b55', 'PAX17**b55',
       'PK11**b55', 'PK31**b55', 'LT1165**b55', 'PK17**b55', 'LT915**b55',
       '1410**a16', '1537B**a16', '1540A**a16', '1542**a16', '1553A**a16',
       '1563**a16', '1564**a16', 'H1601**a16', 'H1603**a16', 'H1610**a16',
       'H1614A2**a16', 'SA61**a16', 'SA62**a16', 'SA65**a16', 'SA70**a16',
       'SA71**a16', 'CB2004**3sti', 'HC15**3sti', 'CB2010**3sti',
       'HC9**3sti', 'HC10**3sti', 'CB2006**3sti', 'CB2005**3sti',
       'CB2002**3sti'], dtype=object)

In [65]:
m5d_donoragg.groupby(['donor_category3', 'unique_donor'], as_index=False).size().groupby(['donor_category3'])['unique_donor'].size()

donor_category3
CB        11
adult     26
infant    55
Name: unique_donor, dtype: int64

In [66]:
print(m5d_donoragg.shape)

(354750, 22)

In [67]:
df_6=m5d_donoragg[m5d_donoragg['unique_donor'].isin(['SA70**a16', 'SA65**a16', 'HC3**afs2', 'HC4**afs2', 'HC3**b4', 'HC7**b4'])]
df_6.groupby('unique_donor')['cdr3aa'].count()

unique_donor
HC3**afs2     509
HC3**b4      1804
HC4**afs2     969
HC7**b4      3646
SA65**a16     489
SA70**a16     686
Name: cdr3aa, dtype: int64

In [68]:
m5d_donoragg=m5d_donoragg[~m5d_donoragg['unique_donor'].isin(['HC3**afs2', 'SA65**a16', 'SA70**a16'])]

In [69]:
m5d_donoragg.groupby(['donor_category3', 'unique_donor'], as_index=False).size().groupby(['donor_category3'])['unique_donor'].size()

donor_category3
CB        11
adult     23
infant    55
Name: unique_donor, dtype: int64

In [70]:
print(m5d_donoragg.shape)

(353066, 22)

## calculate the n_insertion

In [71]:
m5d_donoragg['n_insertion'] = 10000

In [72]:
m5d_donoragg['n_insertion']=np.where(m5d_donoragg['d']!='.', m5d_donoragg['DStart']-m5d_donoragg['VEnd']-1 + m5d_donoragg['JStart'] - m5d_donoragg['DEnd'] - 1, m5d_donoragg['n_insertion'])
m5d_donoragg['n_insertion']=np.where(m5d_donoragg['d']=='.', m5d_donoragg['JStart']-m5d_donoragg['VEnd']-1, m5d_donoragg['n_insertion'])

m5d_donoragg['n_insertion'].unique()

array([  4,   0,  -9,  14,  13,   2,   1,   8,   5,   3,  10,   9,   6,
        11,  20,  12,   7,  -2,  27,  25,  16,  23,  19,  15,  18,  -4,
        -1, -10,  -8, -14,  21,  -5,  17,  22,  28,  26,  24,  32,  33,
        -3,  35,  31,  29,  30,  41, -12,  34,  44,  38,  47,  -7, -11,
        36,  37,  45,  40,  43, -13,  46,  -6,  60,  52,  39,  42,  59,
        62,  58,  53,  81,  49,  51,  48,  55, -21, -19,  65,  67,  57,
        61,  50,  56,  54,  73,  72, -17])

In [73]:
m5d_donoragg.to_csv('../data/output_data/m5d_donoragg.csv', index=False)

In [74]:
# m5d_donoragg.to_csv('/home/lihua/Rcode/TCRdist/m5d_donoragg.csv', index=False)

## Prepare the input data for TCRdist3

In [75]:
# prepare unique amino acid sequence for each donor since different cdr3nt can be translated into the same aa sequence.
# data.groupby('month', as_index=False).agg({"duration": "sum"})

print(m5d_donoragg.shape)

m5d_donoragg_aa = m5d_donoragg.groupby(['donor', 'pheno', 'dataset', 'donor_category', 'donor_category3', 'unique_donor',
                                        'cdr3aa_translated', 'cdr3aa_string', 'aastring_length'], as_index=False).agg({
    'txt': [lambda x: '*'.join(x), 'first', 'last'],
    'count': [lambda x: x.unique(), 'sum'],
    'cdr3nt': [lambda x: '__'.join(x), 'first', 'last'],
    'v': [lambda x: '__'.join(x), 'first', 'last'],
    'd': [lambda x: '__'.join(x), 'first', 'last'],
    'j': [lambda x: '__'.join(x), 'first', 'last']
})

print(m5d_donoragg_aa.shape)
m5d_donoragg_aa.head()

(353066, 23)
(319355, 26)

  donor    pheno dataset donor_category donor_category3 unique_donor  \

0  1410  nopheno     a16          adult           adult    1410**a16
1  1410  nopheno     a16          adult           adult    1410**a16
2  1410  nopheno     a16          adult           adult    1410**a16
3  1410  nopheno     a16          adult           adult    1410**a16
4  1410  nopheno     a16          adult           adult    1410**a16

                                   cdr3aa_translated         cdr3aa_string  \

0  (C, A, C, A, P, L, G, D, T, E, S, S, W, D, T, ...  CACAPLGDTESSWDTRQMFF
1  (C, A, C, D, A, L, A, G, G, S, Y, T, D, K, L, ...     CACDALAGGSYTDKLIF
2  (C, A, C, D, A, L, Q, V, G, D, T, R, G, D, T, ...  CACDALQVGDTRGDTDKLIF
3         (C, A, C, D, A, V, T, D, S, A, K, L, I, F)        CACDAVTDSAKLIF
4  (C, A, C, D, F, I, A, G, G, S, Q, S, K, D, T, ...  CACDFIAGGSQSKDTRQMFF

  aastring_length                                                txt  \
                                                          <lambda_0>
0              20  VDJTOOLS_.1410-A-PE_S24_L001_R1_001.fastq_XCR.txt
1              17  VDJTOOLS_.1410-A-PE_S24_L001_R1_001.fastq_XCR....
2              20  VDJTOOLS_.1410-A-PE_S24_L001_R1_001.fastq_XCR.txt
3              14  VDJTOOLS_.1410-A-PE_S24_L001_R1_001.fastq_XCR.txt
4              20  VDJTOOLS_.1410-A-PE_S24_L001_R1_001.fastq_XCR.txt

                                                      \
                                               first
0  VDJTOOLS_.1410-A-PE_S24_L001_R1_001.fastq_XCR.txt
1  VDJTOOLS_.1410-A-PE_S24_L001_R1_001.fastq_XCR.txt
2  VDJTOOLS_.1410-A-PE_S24_L001_R1_001.fastq_XCR.txt
3  VDJTOOLS_.1410-A-PE_S24_L001_R1_001.fastq_XCR.txt
4  VDJTOOLS_.1410-A-PE_S24_L001_R1_001.fastq_XCR.txt

                                                          count       \
                                                last <lambda_0>  sum
0  VDJTOOLS_.1410-A-PE_S24_L001_R1_001.fastq_XCR.txt        185  185
1  VDJTOOLS_.1410-A-PE_S24_L001_R1_001.fastq_XCR.txt   [641, 2]  643
2  VDJTOOLS_.1410-A-PE_S24_L001_R1_001.fastq_XCR.txt          1    1
3  VDJTOOLS_.1410-A-PE_S24_L001_R1_001.fastq_XCR.txt          3    3
4  VDJTOOLS_.1410-A-PE_S24_L001_R1_001.fastq_XCR.txt          1    1

                                              cdr3nt  \
                                          <lambda_0>
0  TGTGCCTGTGCGCCTCTGGGGGATACGGAGAGCTCCTGGGACACCC...
1  TGTGCCTGTGACGCCCTCGCTGGGGGATCGTACACCGATAAACTCA...
2  TGTGCCTGTGACGCCCTCCAAGTGGGGGATACGCGAGGGGACACCG...
3         TGTGCCTGTGACGCCGTTACGGATTCCGCTAAACTCATCTTT
4  TGTGCCTGTGACTTCATTGCTGGGGGATCTCAGTCAAAGGACACCC...

                                                      \
                                               first
0  TGTGCCTGTGCGCCTCTGGGGGATACGGAGAGCTCCTGGGACACCC...
1  TGTGCCTGTGACGCCCTCGCTGGGGGATCGTACACCGATAAACTCA...
2  TGTGCCTGTGACGCCCTCCAAGTGGGGGATACGCGAGGGGACACCG...
3         TGTGCCTGTGACGCCGTTACGGATTCCGCTAAACTCATCTTT
4  TGTGCCTGTGACTTCATTGCTGGGGGATCTCAGTCAAAGGACACCC...

                                                                 v         \
                                                last    <lambda_0>  first
0  TGTGCCTGTGCGCCTCTGGGGGATACGGAGAGCTCCTGGGACACCC...         TRDV2  TRDV2
1  TGTGCCTGCGACGCCCTCGCTGGAGGATCGTACACCGATAAACTCA...  TRDV2__TRDV2  TRDV2
2  TGTGCCTGTGACGCCCTCCAAGTGGGGGATACGCGAGGGGACACCG...         TRDV2  TRDV2
3         TGTGCCTGTGACGCCGTTACGGATTCCGCTAAACTCATCTTT         TRDV2  TRDV2
4  TGTGCCTGTGACTTCATTGCTGGGGGATCTCAGTCAAAGGACACCC...         TRDV2  TRDV2

                     d                           j
    last    <lambda_0>  first   last    <lambda_0>  first   last
0  TRDV2         TRDD3  TRDD3  TRDD3         TRDJ3  TRDJ3  TRDJ3
1  TRDV2  TRDD3__TRDD3  TRDD3  TRDD3  TRDJ1__TRDJ1  TRDJ1  TRDJ1
2  TRDV2         TRDD3  TRDD3  TRDD3         TRDJ1  TRDJ1  TRDJ1
3  TRDV2             .      .      .         TRDJ1  TRDJ1  TRDJ1
4  TRDV2         TRDD3  TRDD3  TRDD3         TRDJ3  TRDJ3  TRDJ3

In [76]:
m5d_donoragg_aa.columns = ['donor','pheno','dataset','donor_category','donor_category3',
                           'unique_donor','cdr3aa_translated','cdr3aa_string','aastring_length','txt','txt_first','txt_last',
                           'count_dis','count_sum','cdr3nt_dis','cdr3nt_first','cdr3nt_last','v_dis','v_first','v_last',
                           'd_dis','d_first','d_last','j_dis','j_first','j_last']

In [77]:
# the whole dataframe contain unique cdr3aa_string for each donor, try to count the number that a specific cdr3aa_string appears in all donor 
print(m5d_donoragg_aa.shape)
count_freq = m5d_donoragg_aa['cdr3aa_string'].value_counts().rename_axis('cdr3aa_string').reset_index(name='count_in_difdonor')
count_freq

(319355, 26)

              cdr3aa_string  count_in_difdonor
0            CACDTLGDTDKLIF                 89
1            CACDILGDTDKLIF                 85
2            CACDVLGDTDKLIF                 82
3            CACDTVGDTDKLIF                 82
4        CACDTVLGDTWDTRQMFF                 78
...                     ...                ...
262633  CACDFVQDVSSWDTRQMFF                  1
262634    CACDFVSPDGGYGKLIF                  1
262635   CACDGAGGRSWDTRQMFF                  1
262636       CACDGAGRRGELIF                  1
262637    YALGGVFLGDHTDKLIF                  1

[262638 rows x 2 columns]

In [78]:
print(m5d_donoragg_aa.shape), print(count_freq.shape)
m5d_donoragg_aa =  pd.merge(m5d_donoragg_aa, count_freq, on=['cdr3aa_string'], how='left')
print(m5d_donoragg_aa.shape)
m5d_donoragg_aa.head()

(319355, 26)
(262638, 2)
(319355, 27)

,donor,pheno,dataset,donor_category,donor_category3,unique_donor,cdr3aa_translated,cdr3aa_string,aastring_length,txt,txt_first,txt_last,count_dis,count_sum,cdr3nt_dis,cdr3nt_first,cdr3nt_last,v_dis,v_first,v_last,d_dis,d_first,d_last,j_dis,j_first,j_last,count_in_difdonor
0,1410,nopheno,a16,adult,adult,1410**a16,"(C, A, C, A, P, L, G, D, T, E, S, S, W, D, T, ...",CACAPLGDTESSWDTRQMFF,20,VDJTOOLS_.1410-A-PE_S24_L001_R1_001.fastq_XCR.txt,VDJTOOLS_.1410-A-PE_S24_L001_R1_001.fastq_XCR.txt,VDJTOOLS_.1410-A-PE_S24_L001_R1_001.fastq_XCR.txt,185,185,TGTGCCTGTGCGCCTCTGGGGGATACGGAGAGCTCCTGGGACACCC...,TGTGCCTGTGCGCCTCTGGGGGATACGGAGAGCTCCTGGGACACCC...,TGTGCCTGTGCGCCTCTGGGGGATACGGAGAGCTCCTGGGACACCC...,TRDV2,TRDV2,TRDV2,TRDD3,TRDD3,TRDD3,TRDJ3,TRDJ3,TRDJ3,1
1,1410,nopheno,a16,adult,adult,1410**a16,"(C, A, C, D, A, L, A, G, G, S, Y, T, D, K, L, ...",CACDALAGGSYTDKLIF,17,VDJTOOLS_.1410-A-PE_S24_L001_R1_001.fastq_XCR....,VDJTOOLS_.1410-A-PE_S24_L001_R1_001.fastq_XCR.txt,VDJTOOLS_.1410-A-PE_S24_L001_R1_001.fastq_XCR.txt,"[641, 2]",643,TGTGCCTGTGACGCCCTCGCTGGGGGATCGTACACCGATAAACTCA...,TGTGCCTGTGACGCCCTCGCTGGGGGATCGTACACCGATAAACTCA...,TGTGCCTGCGACGCCCTCGCTGGAGGATCGTACACCGATAAACTCA...,TRDV2__TRDV2,TRDV2,TRDV2,TRDD3__TRDD3,TRDD3,TRDD3,TRDJ1__TRDJ1,TRDJ1,TRDJ1,2
2,1410,nopheno,a16,adult,adult,1410**a16,"(C, A, C, D, A, L, Q, V, G, D, T, R, G, D, T, ...",CACDALQVGDTRGDTDKLIF,20,VDJTOOLS_.1410-A-PE_S24_L001_R1_001.fastq_XCR.txt,VDJTOOLS_.1410-A-PE_S24_L001_R1_001.fastq_XCR.txt,VDJTOOLS_.1410-A-PE_S24_L001_R1_001.fastq_XCR.txt,1,1,TGTGCCTGTGACGCCCTCCAAGTGGGGGATACGCGAGGGGACACCG...,TGTGCCTGTGACGCCCTCCAAGTGGGGGATACGCGAGGGGACACCG...,TGTGCCTGTGACGCCCTCCAAGTGGGGGATACGCGAGGGGACACCG...,TRDV2,TRDV2,TRDV2,TRDD3,TRDD3,TRDD3,TRDJ1,TRDJ1,TRDJ1,1
3,1410,nopheno,a16,adult,adult,1410**a16,"(C, A, C, D, A, V, T, D, S, A, K, L, I, F)",CACDAVTDSAKLIF,14,VDJTOOLS_.1410-A-PE_S24_L001_R1_001.fastq_XCR.txt,VDJTOOLS_.1410-A-PE_S24_L001_R1_001.fastq_XCR.txt,VDJTOOLS_.1410-A-PE_S24_L001_R1_001.fastq_XCR.txt,3,3,TGTGCCTGTGACGCCGTTACGGATTCCGCTAAACTCATCTTT,TGTGCCTGTGACGCCGTTACGGATTCCGCTAAACTCATCTTT,TGTGCCTGTGACGCCGTTACGGATTCCGCTAAACTCATCTTT,TRDV2,TRDV2,TRDV2,.,.,.,TRDJ1,TRDJ1,TRDJ1,1
4,1410,nopheno,a16,adult,adult,1410**a16,"(C, A, C, D, F, I, A, G, G, S, Q, S, K, D, T, ...",CACDFIAGGSQSKDTRQMFF,20,VDJTOOLS_.1410-A-PE_S24_L001_R1_001.fastq_XCR.txt,VDJTOOLS_.1410-A-PE_S24_L001_R1_001.fastq_XCR.txt,VDJTOOLS_.1410-A-PE_S24_L001_R1_001.fastq_XCR.txt,1,1,TGTGCCTGTGACTTCATTGCTGGGGGATCTCAGTCAAAGGACACCC...,TGTGCCTGTGACTTCATTGCTGGGGGATCTCAGTCAAAGGACACCC...,TGTGCCTGTGACTTCATTGCTGGGGGATCTCAGTCAAAGGACACCC...,TRDV2,TRDV2,TRDV2,TRDD3,TRDD3,TRDD3,TRDJ3,TRDJ3,TRDJ3,1

In [79]:
print(m5d_donoragg_aa['count_in_difdonor'].min(), m5d_donoragg_aa['count_in_difdonor'].max())
m5d_donoragg_aa['count_in_difdonor'].quantile([0.1, 0.2, 0.25, 0.5, 0.75, 0.8, 0.85, 0.9, 0.95, 1])

1 89

0.10     1.0
0.20     1.0
0.25     1.0
0.50     1.0
0.75     1.0
0.80     2.0
0.85     3.0
0.90     6.0
0.95    16.0
1.00    89.0
Name: count_in_difdonor, dtype: float64

In [80]:
# the bins [1, 2, 3, 4] indicate (1,2], (2,3], (3,4]. 
# define public/private sequence based on whether a sequence occured in multiple donors. 
## using 1 as the threshold
max_count_in_donor=m5d_donoragg_aa['count_in_difdonor'].max()
donor_count = len(m5d_donoragg['unique_donor'].value_counts())
m5d_donoragg_aa['cdr3aa_publicity'] = pd.cut(m5d_donoragg_aa.count_in_difdonor, bins=[0,1,donor_count], labels=['private', 'public'])

## using three different publicity label for the data
m5d_donoragg_aa['publicity3c'] = pd.cut(m5d_donoragg_aa.count_in_difdonor, bins=[0,1,9,donor_count], labels=['private', 'low_public', 'high_public'])
m5d_donoragg_aa['publicity'] = pd.cut(m5d_donoragg_aa.count_in_difdonor, bins=[0,1,9,donor_count], labels=['private', 'low_public', 'high_public'])


## using 5 as the threshold

m5d_donoragg_aa['publicity2'] = pd.cut(m5d_donoragg_aa.count_in_difdonor, bins=[0,2,donor_count], labels=['private', 'public'])

m5d_donoragg_aa['publicity3'] = pd.cut(m5d_donoragg_aa.count_in_difdonor, bins=[0,3,donor_count], labels=['private', 'public'])

m5d_donoragg_aa['publicity5'] = pd.cut(m5d_donoragg_aa.count_in_difdonor, bins=[0,5,donor_count], labels=['private', 'public'])

m5d_donoragg_aa['publicity10'] = pd.cut(m5d_donoragg_aa.count_in_difdonor, bins=[0,10,donor_count], labels=['private', 'public'])

m5d_donoragg_aa['publicity20'] = pd.cut(m5d_donoragg_aa.count_in_difdonor, bins=[0,20,donor_count], labels=['private', 'public'])

m5d_donoragg_aa['publicity30'] = pd.cut(m5d_donoragg_aa.count_in_difdonor, bins=[0,30,donor_count], labels=['private', 'public'])

m5d_donoragg_aa['publicity42'] = pd.cut(m5d_donoragg_aa.count_in_difdonor, bins=[0,42,donor_count], labels=['private', 'public'])

In [81]:
print(m5d_donoragg_aa['count_in_difdonor'].min(), m5d_donoragg_aa['count_in_difdonor'].max())
m5d_donoragg_aa['count_in_difdonor'].quantile([0.1, 0.2, 0.25, 0.5, 0.75, 0.8, 0.85, 0.9, 0.95, 1])

1 89

0.10     1.0
0.20     1.0
0.25     1.0
0.50     1.0
0.75     1.0
0.80     2.0
0.85     3.0
0.90     6.0
0.95    16.0
1.00    89.0
Name: count_in_difdonor, dtype: float64

In [82]:
freq_temp = m5d_donoragg_aa.groupby(['donor', 'dataset'], as_index=False).agg({
    'count_sum': 'sum'
})
freq_temp.columns = ['donor', 'dataset', 'donor_sum']
freq_temp.head()

   donor dataset  donor_sum
0   1410     a16       7703
1  1537B     a16      45797
2  1540A     a16      56724
3   1542     a16      63036
4  1553A     a16      20232

In [83]:
m5d_donoragg_aa = pd.merge(m5d_donoragg_aa, freq_temp, how='left', left_on=['donor', 'dataset'], right_on=['donor', 'dataset'])
m5d_donoragg_aa['aa_freq'] = m5d_donoragg_aa['count_sum'] / m5d_donoragg_aa['donor_sum']

m5d_donoragg_aa.head()

,donor,pheno,dataset,donor_category,donor_category3,unique_donor,cdr3aa_translated,cdr3aa_string,aastring_length,txt,txt_first,txt_last,count_dis,count_sum,cdr3nt_dis,cdr3nt_first,cdr3nt_last,v_dis,v_first,v_last,d_dis,d_first,d_last,j_dis,j_first,j_last,count_in_difdonor,cdr3aa_publicity,publicity3c,publicity,publicity2,publicity3,publicity5,publicity10,publicity20,publicity30,publicity42,donor_sum,aa_freq
0,1410,nopheno,a16,adult,adult,1410**a16,"(C, A, C, A, P, L, G, D, T, E, S, S, W, D, T, ...",CACAPLGDTESSWDTRQMFF,20,VDJTOOLS_.1410-A-PE_S24_L001_R1_001.fastq_XCR.txt,VDJTOOLS_.1410-A-PE_S24_L001_R1_001.fastq_XCR.txt,VDJTOOLS_.1410-A-PE_S24_L001_R1_001.fastq_XCR.txt,185,185,TGTGCCTGTGCGCCTCTGGGGGATACGGAGAGCTCCTGGGACACCC...,TGTGCCTGTGCGCCTCTGGGGGATACGGAGAGCTCCTGGGACACCC...,TGTGCCTGTGCGCCTCTGGGGGATACGGAGAGCTCCTGGGACACCC...,TRDV2,TRDV2,TRDV2,TRDD3,TRDD3,TRDD3,TRDJ3,TRDJ3,TRDJ3,1,private,private,private,private,private,private,private,private,private,private,7703,0.024017
1,1410,nopheno,a16,adult,adult,1410**a16,"(C, A, C, D, A, L, A, G, G, S, Y, T, D, K, L, ...",CACDALAGGSYTDKLIF,17,VDJTOOLS_.1410-A-PE_S24_L001_R1_001.fastq_XCR....,VDJTOOLS_.1410-A-PE_S24_L001_R1_001.fastq_XCR.txt,VDJTOOLS_.1410-A-PE_S24_L001_R1_001.fastq_XCR.txt,"[641, 2]",643,TGTGCCTGTGACGCCCTCGCTGGGGGATCGTACACCGATAAACTCA...,TGTGCCTGTGACGCCCTCGCTGGGGGATCGTACACCGATAAACTCA...,TGTGCCTGCGACGCCCTCGCTGGAGGATCGTACACCGATAAACTCA...,TRDV2__TRDV2,TRDV2,TRDV2,TRDD3__TRDD3,TRDD3,TRDD3,TRDJ1__TRDJ1,TRDJ1,TRDJ1,2,public,low_public,low_public,private,private,private,private,private,private,private,7703,0.083474
2,1410,nopheno,a16,adult,adult,1410**a16,"(C, A, C, D, A, L, Q, V, G, D, T, R, G, D, T, ...",CACDALQVGDTRGDTDKLIF,20,VDJTOOLS_.1410-A-PE_S24_L001_R1_001.fastq_XCR.txt,VDJTOOLS_.1410-A-PE_S24_L001_R1_001.fastq_XCR.txt,VDJTOOLS_.1410-A-PE_S24_L001_R1_001.fastq_XCR.txt,1,1,TGTGCCTGTGACGCCCTCCAAGTGGGGGATACGCGAGGGGACACCG...,TGTGCCTGTGACGCCCTCCAAGTGGGGGATACGCGAGGGGACACCG...,TGTGCCTGTGACGCCCTCCAAGTGGGGGATACGCGAGGGGACACCG...,TRDV2,TRDV2,TRDV2,TRDD3,TRDD3,TRDD3,TRDJ1,TRDJ1,TRDJ1,1,private,private,private,private,private,private,private,private,private,private,7703,0.000130
3,1410,nopheno,a16,adult,adult,1410**a16,"(C, A, C, D, A, V, T, D, S, A, K, L, I, F)",CACDAVTDSAKLIF,14,VDJTOOLS_.1410-A-PE_S24_L001_R1_001.fastq_XCR.txt,VDJTOOLS_.1410-A-PE_S24_L001_R1_001.fastq_XCR.txt,VDJTOOLS_.1410-A-PE_S24_L001_R1_001.fastq_XCR.txt,3,3,TGTGCCTGTGACGCCGTTACGGATTCCGCTAAACTCATCTTT,TGTGCCTGTGACGCCGTTACGGATTCCGCTAAACTCATCTTT,TGTGCCTGTGACGCCGTTACGGATTCCGCTAAACTCATCTTT,TRDV2,TRDV2,TRDV2,.,.,.,TRDJ1,TRDJ1,TRDJ1,1,private,private,private,private,private,private,private,private,private,private,7703,0.000389
4,1410,nopheno,a16,adult,adult,1410**a16,"(C, A, C, D, F, I, A, G, G, S, Q, S, K, D, T, ...",CACDFIAGGSQSKDTRQMFF,20,VDJTOOLS_.1410-A-PE_S24_L001_R1_001.fastq_XCR.txt,VDJTOOLS_.1410-A-PE_S24_L001_R1_001.fastq_XCR.txt,VDJTOOLS_.1410-A-PE_S24_L001_R1_001.fastq_XCR.txt,1,1,TGTGCCTGTGACTTCATTGCTGGGGGATCTCAGTCAAAGGACACCC...,TGTGCCTGTGACTTCATTGCTGGGGGATCTCAGTCAAAGGACACCC...,TGTGCCTGTGACTTCATTGCTGGGGGATCTCAGTCAAAGGACACCC...,TRDV2,TRDV2,TRDV2,TRDD3,TRDD3,TRDD3,TRDJ3,TRDJ3,TRDJ3,1,private,private,private,private,private,private,private,private,private,private,7703,0.000130

In [84]:
### plot the public sequence number / private sequence number for each donor according to the frequence group.
### assign a threshold of 75% quantile for each donoror for defining the low/high frequence label

for i in ['10', '15', '20', '25', '50', '75', '80', '85', '90', '95']:
    
    quantile_name='quantile_' + i
    column_name='cut_'+quantile_name 
    m5d_donoragg_aa[quantile_name] = 0
    m5d_donoragg_aa[column_name] = 'low_freq'
    
    for donor in m5d_donoragg_aa['unique_donor'].unique():
        q_quantile = m5d_donoragg_aa[m5d_donoragg_aa['unique_donor']==donor]['aa_freq'].quantile(int(i)/100)
        
        m5d_donoragg_aa.loc[m5d_donoragg_aa['unique_donor'] == donor, quantile_name] = q_quantile
        m5d_donoragg_aa.loc[(m5d_donoragg_aa['unique_donor'] == donor) & (m5d_donoragg_aa['aa_freq'] >= q_quantile), column_name] = 'high_freq'

In [85]:
## define high/low_freq sequence label:
## using the quantile number, 0.25. 0.5, 0.75


m5d_donoragg_aa['quantile_8'] = 0
m5d_donoragg_aa['cut_quantile_8'] = 'low_freq'
quantile_8 = []
condition = []

for i in m5d_donoragg_aa['unique_donor'].unique():
    q_temp = m5d_donoragg_aa[m5d_donoragg_aa['unique_donor']==i]['aa_freq'].quantile(0.75)
    # quantile_8.append(q_temp)
    m5d_donoragg_aa['quantile_8'] = np.where(m5d_donoragg_aa['unique_donor'] == i, q_temp, m5d_donoragg_aa.quantile_8)
    m5d_donoragg_aa['cut_quantile_8'] = np.where((m5d_donoragg_aa['unique_donor'] == i) & (m5d_donoragg_aa['aa_freq'] >= q_temp), 'high_freq', m5d_donoragg_aa.cut_quantile_8)

In [86]:
# check the number of different label combination (public/private, high/low_freq)

for pub in ['cdr3aa_publicity', 'publicity', 'publicity3c','publicity2','publicity3', 
            'publicity5', 'publicity10', 'publicity20', 'publicity30', 'publicity42']:
    for freq in ['cut_quantile_10', 'cut_quantile_15', 'cut_quantile_20','cut_quantile_25', 'cut_quantile_50', 
                 'cut_quantile_75', 'cut_quantile_80','cut_quantile_85','cut_quantile_90', 'cut_quantile_95']:
        a = m5d_donoragg_aa.groupby(['unique_donor', freq, pub], as_index=False).size()
        print(pub, freq, a[a['size']==0].shape, '\n', a[a['size']==0])  
        print('-----------------------------------------------------')

cdr3aa_publicity cut_quantile_10 (176, 4)
     unique_donor cut_quantile_10 cdr3aa_publicity  size
2      1410**a16        low_freq          private     0
3      1410**a16        low_freq           public     0
6     1537B**a16        low_freq          private     0
7     1537B**a16        low_freq           public     0
10    1540A**a16        low_freq          private     0
..           ...             ...              ...   ...
347    SA61**a16        low_freq           public     0
350    SA62**a16        low_freq          private     0
351    SA62**a16        low_freq           public     0
354    SA71**a16        low_freq          private     0
355    SA71**a16        low_freq           public     0

[176 rows x 4 columns]
-----------------------------------------------------
cdr3aa_publicity cut_quantile_15 (168, 4)
     unique_donor cut_quantile_15 cdr3aa_publicity  size
2      1410**a16        low_freq          private     0
3      1410**a16        low_freq           public     0
6     1537B**a16        low_freq          private     0
7     1537B**a16        low_freq           public     0
10    1540A**a16        low_freq          private     0
..           ...             ...              ...   ...
347    SA61**a16        low_freq           public     0
350    SA62**a16        low_freq          private     0
351    SA62**a16        low_freq           public     0
354    SA71**a16        low_freq          private     0
355    SA71**a16        low_freq           public     0

[168 rows x 4 columns]
-----------------------------------------------------
cdr3aa_publicity cut_quantile_20 (140, 4)
     unique_donor cut_quantile_20 cdr3aa_publicity  size
2      1410**a16        low_freq          private     0
3      1410**a16        low_freq           public     0
10    1540A**a16        low_freq          private     0
11    1540A**a16        low_freq           public     0
18    1553A**a16        low_freq          private     0
..           ...             ...              ...   ...
347    SA61**a16        low_freq           public     0
350    SA62**a16        low_freq          private     0
351    SA62**a16        low_freq           public     0
354    SA71**a16        low_freq          private     0
355    SA71**a16        low_freq           public     0

[140 rows x 4 columns]
-----------------------------------------------------
cdr3aa_publicity cut_quantile_25 (94, 4)
     unique_donor cut_quantile_25 cdr3aa_publicity  size
2      1410**a16        low_freq          private     0
3      1410**a16        low_freq           public     0
10    1540A**a16        low_freq          private     0
11    1540A**a16        low_freq           public     0
22     1563**a16        low_freq          private     0
..           ...             ...              ...   ...
339     PK7**b55        low_freq           public     0
342     PK8**b55        low_freq          private     0
343     PK8**b55        low_freq           public     0
350    SA62**a16        low_freq          private     0
351    SA62**a16        low_freq           public     0

[94 rows x 4 columns]
-----------------------------------------------------
cdr3aa_publicity cut_quantile_50 (0, 4)
 Empty DataFrame
Columns: [unique_donor, cut_quantile_50, cdr3aa_publicity, size]
Index: []
-----------------------------------------------------
cdr3aa_publicity cut_quantile_75 (0, 4)
 Empty DataFrame
Columns: [unique_donor, cut_quantile_75, cdr3aa_publicity, size]
Index: []
-----------------------------------------------------
cdr3aa_publicity cut_quantile_80 (1, 4)
     unique_donor cut_quantile_80 cdr3aa_publicity  size
240     PK1**b55       high_freq          private     0
-----------------------------------------------------
cdr3aa_publicity cut_quantile_85 (1, 4)
     unique_donor cut_quantile_85 cdr3aa_publicity  size
240     PK1**b55       high_freq          private     0
-----------------------------------------------------
cdr3aa_publicity cut_quantile_90 (1, 4)
     unique_donor cut_quantile_90 cdr3aa_publicity  size
240     PK1**b55       high_freq          private     0
-----------------------------------------------------
cdr3aa_publicity cut_quantile_95 (5, 4)
     unique_donor cut_quantile_95 cdr3aa_publicity  size
73    H1601**a16       high_freq           public     0
240     PK1**b55       high_freq          private     0
248    PK11**b55       high_freq          private     0
268    PK19**b55       high_freq          private     0
292    PK24**b55       high_freq          private     0
-----------------------------------------------------
publicity cut_quantile_10 (264, 4)
     unique_donor cut_quantile_10    publicity  size
3      1410**a16        low_freq      private     0
4      1410**a16        low_freq   low_public     0
5      1410**a16        low_freq  high_public     0
9     1537B**a16        low_freq      private     0
10    1537B**a16        low_freq   low_public     0
..           ...             ...          ...   ...
526    SA62**a16        low_freq   low_public     0
527    SA62**a16        low_freq  high_public     0
531    SA71**a16        low_freq      private     0
532    SA71**a16        low_freq   low_public     0
533    SA71**a16        low_freq  high_public     0

[264 rows x 4 columns]
-----------------------------------------------------
publicity cut_quantile_15 (253, 4)
     unique_donor cut_quantile_15    publicity  size
3      1410**a16        low_freq      private     0
4      1410**a16        low_freq   low_public     0
5      1410**a16        low_freq  high_public     0
9     1537B**a16        low_freq      private     0
10    1537B**a16        low_freq   low_public     0
..           ...             ...          ...   ...
526    SA62**a16        low_freq   low_public     0
527    SA62**a16        low_freq  high_public     0
531    SA71**a16        low_freq      private     0
532    SA71**a16        low_freq   low_public     0
533    SA71**a16        low_freq  high_public     0

[253 rows x 4 columns]
-----------------------------------------------------
publicity cut_quantile_20 (210, 4)
     unique_donor cut_quantile_20    publicity  size
3      1410**a16        low_freq      private     0
4      1410**a16        low_freq   low_public     0
5      1410**a16        low_freq  high_public     0
15    1540A**a16        low_freq      private     0
16    1540A**a16        low_freq   low_public     0
..           ...             ...          ...   ...
526    SA62**a16        low_freq   low_public     0
527    SA62**a16        low_freq  high_public     0
531    SA71**a16        low_freq      private     0
532    SA71**a16        low_freq   low_public     0
533    SA71**a16        low_freq  high_public     0

[210 rows x 4 columns]
-----------------------------------------------------
publicity cut_quantile_25 (141, 4)
     unique_donor cut_quantile_25    publicity  size
3      1410**a16        low_freq      private     0
4      1410**a16        low_freq   low_public     0
5      1410**a16        low_freq  high_public     0
15    1540A**a16        low_freq      private     0
16    1540A**a16        low_freq   low_public     0
..           ...             ...          ...   ...
514     PK8**b55        low_freq   low_public     0
515     PK8**b55        low_freq  high_public     0
525    SA62**a16        low_freq      private     0
526    SA62**a16        low_freq   low_public     0
527    SA62**a16        low_freq  high_public     0

[141 rows x 4 columns]
-----------------------------------------------------
publicity cut_quantile_50 (2, 4)
     unique_donor cut_quantile_50    publicity  size
17    1540A**a16        low_freq  high_public     0
113   H1601**a16        low_freq  high_public     0
-----------------------------------------------------
publicity cut_quantile_75 (1, 4)
     unique_donor cut_quantile_75    publicity  size
110   H1601**a16       high_freq  high_public     0
-----------------------------------------------------
publicity cut_quantile_80 (2, 4)
     unique_donor cut_quantile_80    publicity  size
110   H1601**a16       high_freq  high_public     0
360     PK1**b55       high_freq      private     0
-----------------------------------------------------
publicity cut_quantile_85 (3, 4)
     unique_donor cut_quantile_85    publicity  size
2      1410**a16       high_freq  high_public     0
110   H1601**a16       high_freq  high_public     0
360     PK1**b55       high_freq      private     0
-----------------------------------------------------
publicity cut_quantile_90 (3, 4)
     unique_donor cut_quantile_90    publicity  size
2      1410**a16       high_freq  high_public     0
110   H1601**a16       high_freq  high_public     0
360     PK1**b55       high_freq      private     0
-----------------------------------------------------
publicity cut_quantile_95 (8, 4)
     unique_donor cut_quantile_95    publicity  size
2      1410**a16       high_freq  high_public     0
38     1564**a16       high_freq  high_public     0
109   H1601**a16       high_freq   low_public     0
110   H1601**a16       high_freq  high_public     0
360     PK1**b55       high_freq      private     0
372    PK11**b55       high_freq      private     0
402    PK19**b55       high_freq      private     0
438    PK24**b55       high_freq      private     0
-----------------------------------------------------
publicity3c cut_quantile_10 (264, 4)
     unique_donor cut_quantile_10  publicity3c  size
3      1410**a16        low_freq      private     0
4      1410**a16        low_freq   low_public     0
5      1410**a16        low_freq  high_public     0
9     1537B**a16        low_freq      private     0
10    1537B**a16        low_freq   low_public     0
..           ...             ...          ...   ...
526    SA62**a16        low_freq   low_public     0
527    SA62**a16        low_freq  high_public     0
531    SA71**a16        low_freq      private     0
532    SA71**a16        low_freq   low_public     0
533    SA71**a16        low_freq  high_public     0

[264 rows x 4 columns]
-----------------------------------------------------
publicity3c cut_quantile_15 (253, 4)

     unique_donor cut_quantile_15  publicity3c  size
3      1410**a16        low_freq      private     0
4      1410**a16        low_freq   low_public     0
5      1410**a16        low_freq  high_public     0
9     1537B**a16        low_freq      private     0
10    1537B**a16        low_freq   low_public     0
..           ...             ...          ...   ...
526    SA62**a16        low_freq   low_public     0
527    SA62**a16        low_freq  high_public     0
531    SA71**a16        low_freq      private     0
532    SA71**a16        low_freq   low_public     0
533    SA71**a16        low_freq  high_public     0

[253 rows x 4 columns]
-----------------------------------------------------
publicity3c cut_quantile_20 (210, 4)
     unique_donor cut_quantile_20  publicity3c  size
3      1410**a16        low_freq      private     0
4      1410**a16        low_freq   low_public     0
5      1410**a16        low_freq  high_public     0
15    1540A**a16        low_freq      private     0
16    1540A**a16        low_freq   low_public     0
..           ...             ...          ...   ...
526    SA62**a16        low_freq   low_public     0
527    SA62**a16        low_freq  high_public     0
531    SA71**a16        low_freq      private     0
532    SA71**a16        low_freq   low_public     0
533    SA71**a16        low_freq  high_public     0

[210 rows x 4 columns]
-----------------------------------------------------
publicity3c cut_quantile_25 (141, 4)
     unique_donor cut_quantile_25  publicity3c  size
3      1410**a16        low_freq      private     0
4      1410**a16        low_freq   low_public     0
5      1410**a16        low_freq  high_public     0
15    1540A**a16        low_freq      private     0
16    1540A**a16        low_freq   low_public     0
..           ...             ...          ...   ...
514     PK8**b55        low_freq   low_public     0
515     PK8**b55        low_freq  high_public     0
525    SA62**a16        low_freq      private     0
526    SA62**a16        low_freq   low_public     0
527    SA62**a16        low_freq  high_public     0

[141 rows x 4 columns]
-----------------------------------------------------
publicity3c cut_quantile_50 (2, 4)
     unique_donor cut_quantile_50  publicity3c  size
17    1540A**a16        low_freq  high_public     0
113   H1601**a16        low_freq  high_public     0
-----------------------------------------------------
publicity3c cut_quantile_75 (1, 4)
     unique_donor cut_quantile_75  publicity3c  size
110   H1601**a16       high_freq  high_public     0
-----------------------------------------------------
publicity3c cut_quantile_80 (2, 4)
     unique_donor cut_quantile_80  publicity3c  size
110   H1601**a16       high_freq  high_public     0
360     PK1**b55       high_freq      private     0
-----------------------------------------------------
publicity3c cut_quantile_85 (3, 4)
     unique_donor cut_quantile_85  publicity3c  size
2      1410**a16       high_freq  high_public     0
110   H1601**a16       high_freq  high_public     0
360     PK1**b55       high_freq      private     0
-----------------------------------------------------
publicity3c cut_quantile_90 (3, 4)
     unique_donor cut_quantile_90  publicity3c  size
2      1410**a16       high_freq  high_public     0
110   H1601**a16       high_freq  high_public     0
360     PK1**b55       high_freq      private     0
-----------------------------------------------------
publicity3c cut_quantile_95 (8, 4)
     unique_donor cut_quantile_95  publicity3c  size
2      1410**a16       high_freq  high_public     0
38     1564**a16       high_freq  high_public     0
109   H1601**a16       high_freq   low_public     0
110   H1601**a16       high_freq  high_public     0
360     PK1**b55       high_freq      private     0
372    PK11**b55       high_freq      private     0
402    PK19**b55       high_freq      private     0
438    PK24**b55       high_freq      private     0
-----------------------------------------------------
publicity2 cut_quantile_10 (176, 4)
     unique_donor cut_quantile_10 publicity2  size
2      1410**a16        low_freq    private     0
3      1410**a16        low_freq     public     0
6     1537B**a16        low_freq    private     0
7     1537B**a16        low_freq     public     0
10    1540A**a16        low_freq    private     0
..           ...             ...        ...   ...
347    SA61**a16        low_freq     public     0
350    SA62**a16        low_freq    private     0
351    SA62**a16        low_freq     public     0
354    SA71**a16        low_freq    private     0
355    SA71**a16        low_freq     public     0

[176 rows x 4 columns]
-----------------------------------------------------
publicity2 cut_quantile_15 (168, 4)
     unique_donor cut_quantile_15 publicity2  size
2      1410**a16        low_freq    private     0
3      1410**a16        low_freq     public     0
6     1537B**a16        low_freq    private     0
7     1537B**a16        low_freq     public     0
10    1540A**a16        low_freq    private     0
..           ...             ...        ...   ...
347    SA61**a16        low_freq     public     0
350    SA62**a16        low_freq    private     0
351    SA62**a16        low_freq     public     0
354    SA71**a16        low_freq    private     0
355    SA71**a16        low_freq     public     0

[168 rows x 4 columns]
-----------------------------------------------------
publicity2 cut_quantile_20 (140, 4)
     unique_donor cut_quantile_20 publicity2  size
2      1410**a16        low_freq    private     0
3      1410**a16        low_freq     public     0
10    1540A**a16        low_freq    private     0
11    1540A**a16        low_freq     public     0
18    1553A**a16        low_freq    private     0
..           ...             ...        ...   ...
347    SA61**a16        low_freq     public     0
350    SA62**a16        low_freq    private     0
351    SA62**a16        low_freq     public     0
354    SA71**a16        low_freq    private     0
355    SA71**a16        low_freq     public     0

[140 rows x 4 columns]
-----------------------------------------------------
publicity2 cut_quantile_25 (94, 4)
     unique_donor cut_quantile_25 publicity2  size
2      1410**a16        low_freq    private     0
3      1410**a16        low_freq     public     0
10    1540A**a16        low_freq    private     0
11    1540A**a16        low_freq     public     0
22     1563**a16        low_freq    private     0
..           ...             ...        ...   ...
339     PK7**b55        low_freq     public     0
342     PK8**b55        low_freq    private     0
343     PK8**b55        low_freq     public     0
350    SA62**a16        low_freq    private     0
351    SA62**a16        low_freq     public     0

[94 rows x 4 columns]
-----------------------------------------------------
publicity2 cut_quantile_50 (0, 4)
 Empty DataFrame
Columns: [unique_donor, cut_quantile_50, publicity2, size]
Index: []
-----------------------------------------------------
publicity2 cut_quantile_75 (0, 4)
 Empty DataFrame
Columns: [unique_donor, cut_quantile_75, publicity2, size]
Index: []
-----------------------------------------------------
publicity2 cut_quantile_80 (0, 4)
 Empty DataFrame
Columns: [unique_donor, cut_quantile_80, publicity2, size]
Index: []
-----------------------------------------------------
publicity2 cut_quantile_85 (0, 4)
 Empty DataFrame
Columns: [unique_donor, cut_quantile_85, publicity2, size]
Index: []
-----------------------------------------------------
publicity2 cut_quantile_90 (0, 4)
 Empty DataFrame
Columns: [unique_donor, cut_quantile_90, publicity2, size]
Index: []
-----------------------------------------------------
publicity2 cut_quantile_95 (2, 4)
     unique_donor cut_quantile_95 publicity2  size
73    H1601**a16       high_freq     public     0
268    PK19**b55       high_freq    private     0
-----------------------------------------------------
publicity3 cut_quantile_10 (176, 4)
     unique_donor cut_quantile_10 publicity3  size
2      1410**a16        low_freq    private     0
3      1410**a16        low_freq     public     0
6     1537B**a16        low_freq    private     0
7     1537B**a16        low_freq     public     0
10    1540A**a16        low_freq    private     0
..           ...             ...        ...   ...
347    SA61**a16        low_freq     public     0
350    SA62**a16        low_freq    private     0
351    SA62**a16        low_freq     public     0
354    SA71**a16        low_freq    private     0
355    SA71**a16        low_freq     public     0

[176 rows x 4 columns]
-----------------------------------------------------
publicity3 cut_quantile_15 (168, 4)
     unique_donor cut_quantile_15 publicity3  size
2      1410**a16        low_freq    private     0
3      1410**a16        low_freq     public     0
6     1537B**a16        low_freq    private     0
7     1537B**a16        low_freq     public     0
10    1540A**a16        low_freq    private     0
..           ...             ...        ...   ...
347    SA61**a16        low_freq     public     0
350    SA62**a16        low_freq    private     0
351    SA62**a16        low_freq     public     0
354    SA71**a16        low_freq    private     0
355    SA71**a16        low_freq     public     0

[168 rows x 4 columns]
-----------------------------------------------------
publicity3 cut_quantile_20 (140, 4)
     unique_donor cut_quantile_20 publicity3  size
2      1410**a16        low_freq    private     0
3      1410**a16        low_freq     public     0
10    1540A**a16        low_freq    private     0
11    1540A**a16        low_freq     public     0
18    1553A**a16        low_freq    private     0
..           ...             ...        ...   ...
347    SA61**a16        low_freq     public     0
350    SA62**a16        low_freq    private     0
351    SA62**a16        low_freq     public     0
354    SA71**a16        low_freq    private     0
355    SA71**a16        low_freq     public     0

[140 rows x 4 columns]
-----------------------------------------------------
publicity3 cut_quantile_25 (94, 4)
     unique_donor cut_quantile_25 publicity3  size
2      1410**a16        low_freq    private     0
3      1410**a16        low_freq     public     0
10    1540A**a16        low_freq    private     0
11    1540A**a16        low_freq     public     0
22     1563**a16        low_freq    private     0
..           ...             ...        ...   ...
339     PK7**b55        low_freq     public     0
342     PK8**b55        low_freq    private     0
343     PK8**b55        low_freq     public     0
350    SA62**a16        low_freq    private     0
351    SA62**a16        low_freq     public     0

[94 rows x 4 columns]
-----------------------------------------------------
publicity3 cut_quantile_50 (1, 4)
    unique_donor cut_quantile_50 publicity3  size
75   H1601**a16        low_freq     public     0
-----------------------------------------------------

publicity3 cut_quantile_75 (1, 4)
    unique_donor cut_quantile_75 publicity3  size
73   H1601**a16       high_freq     public     0
-----------------------------------------------------
publicity3 cut_quantile_80 (1, 4)
    unique_donor cut_quantile_80 publicity3  size
73   H1601**a16       high_freq     public     0
-----------------------------------------------------
publicity3 cut_quantile_85 (1, 4)
    unique_donor cut_quantile_85 publicity3  size
73   H1601**a16       high_freq     public     0
-----------------------------------------------------
publicity3 cut_quantile_90 (1, 4)
    unique_donor cut_quantile_90 publicity3  size
73   H1601**a16       high_freq     public     0
-----------------------------------------------------
publicity3 cut_quantile_95 (2, 4)
    unique_donor cut_quantile_95 publicity3  size
1     1410**a16       high_freq     public     0
73   H1601**a16       high_freq     public     0
-----------------------------------------------------
publicity5 cut_quantile_10 (176, 4)
     unique_donor cut_quantile_10 publicity5  size
2      1410**a16        low_freq    private     0
3      1410**a16        low_freq     public     0
6     1537B**a16        low_freq    private     0
7     1537B**a16        low_freq     public     0
10    1540A**a16        low_freq    private     0
..           ...             ...        ...   ...
347    SA61**a16        low_freq     public     0
350    SA62**a16        low_freq    private     0
351    SA62**a16        low_freq     public     0
354    SA71**a16        low_freq    private     0
355    SA71**a16        low_freq     public     0

[176 rows x 4 columns]
-----------------------------------------------------
publicity5 cut_quantile_15 (168, 4)
     unique_donor cut_quantile_15 publicity5  size
2      1410**a16        low_freq    private     0
3      1410**a16        low_freq     public     0
6     1537B**a16        low_freq    private     0
7     1537B**a16        low_freq     public     0
10    1540A**a16        low_freq    private     0
..           ...             ...        ...   ...
347    SA61**a16        low_freq     public     0
350    SA62**a16        low_freq    private     0
351    SA62**a16        low_freq     public     0
354    SA71**a16        low_freq    private     0
355    SA71**a16        low_freq     public     0

[168 rows x 4 columns]
-----------------------------------------------------
publicity5 cut_quantile_20 (140, 4)
     unique_donor cut_quantile_20 publicity5  size
2      1410**a16        low_freq    private     0
3      1410**a16        low_freq     public     0
10    1540A**a16        low_freq    private     0
11    1540A**a16        low_freq     public     0
18    1553A**a16        low_freq    private     0
..           ...             ...        ...   ...
347    SA61**a16        low_freq     public     0
350    SA62**a16        low_freq    private     0
351    SA62**a16        low_freq     public     0
354    SA71**a16        low_freq    private     0
355    SA71**a16        low_freq     public     0

[140 rows x 4 columns]
-----------------------------------------------------
publicity5 cut_quantile_25 (94, 4)
     unique_donor cut_quantile_25 publicity5  size
2      1410**a16        low_freq    private     0
3      1410**a16        low_freq     public     0
10    1540A**a16        low_freq    private     0
11    1540A**a16        low_freq     public     0
22     1563**a16        low_freq    private     0
..           ...             ...        ...   ...
339     PK7**b55        low_freq     public     0
342     PK8**b55        low_freq    private     0
343     PK8**b55        low_freq     public     0
350    SA62**a16        low_freq    private     0
351    SA62**a16        low_freq     public     0

[94 rows x 4 columns]
-----------------------------------------------------
publicity5 cut_quantile_50 (1, 4)
    unique_donor cut_quantile_50 publicity5  size
75   H1601**a16        low_freq     public     0
-----------------------------------------------------
publicity5 cut_quantile_75 (1, 4)
    unique_donor cut_quantile_75 publicity5  size
73   H1601**a16       high_freq     public     0
-----------------------------------------------------
publicity5 cut_quantile_80 (1, 4)
    unique_donor cut_quantile_80 publicity5  size
73   H1601**a16       high_freq     public     0
-----------------------------------------------------
publicity5 cut_quantile_85 (2, 4)
    unique_donor cut_quantile_85 publicity5  size
1     1410**a16       high_freq     public     0
73   H1601**a16       high_freq     public     0
-----------------------------------------------------
publicity5 cut_quantile_90 (2, 4)
    unique_donor cut_quantile_90 publicity5  size
1     1410**a16       high_freq     public     0
73   H1601**a16       high_freq     public     0
-----------------------------------------------------
publicity5 cut_quantile_95 (2, 4)
    unique_donor cut_quantile_95 publicity5  size
1     1410**a16       high_freq     public     0
73   H1601**a16       high_freq     public     0
-----------------------------------------------------
publicity10 cut_quantile_10 (176, 4)
     unique_donor cut_quantile_10 publicity10  size
2      1410**a16        low_freq     private     0
3      1410**a16        low_freq      public     0
6     1537B**a16        low_freq     private     0
7     1537B**a16        low_freq      public     0
10    1540A**a16        low_freq     private     0
..           ...             ...         ...   ...
347    SA61**a16        low_freq      public     0
350    SA62**a16        low_freq     private     0
351    SA62**a16        low_freq      public     0
354    SA71**a16        low_freq     private     0
355    SA71**a16        low_freq      public     0

[176 rows x 4 columns]
-----------------------------------------------------
publicity10 cut_quantile_15 (169, 4)
     unique_donor cut_quantile_15 publicity10  size
2      1410**a16        low_freq     private     0
3      1410**a16        low_freq      public     0
6     1537B**a16        low_freq     private     0
7     1537B**a16        low_freq      public     0
10    1540A**a16        low_freq     private     0
..           ...             ...         ...   ...
347    SA61**a16        low_freq      public     0
350    SA62**a16        low_freq     private     0
351    SA62**a16        low_freq      public     0
354    SA71**a16        low_freq     private     0
355    SA71**a16        low_freq      public     0

[169 rows x 4 columns]
-----------------------------------------------------
publicity10 cut_quantile_20 (140, 4)
     unique_donor cut_quantile_20 publicity10  size
2      1410**a16        low_freq     private     0
3      1410**a16        low_freq      public     0
10    1540A**a16        low_freq     private     0
11    1540A**a16        low_freq      public     0
18    1553A**a16        low_freq     private     0
..           ...             ...         ...   ...
347    SA61**a16        low_freq      public     0
350    SA62**a16        low_freq     private     0
351    SA62**a16        low_freq      public     0
354    SA71**a16        low_freq     private     0
355    SA71**a16        low_freq      public     0

[140 rows x 4 columns]
-----------------------------------------------------
publicity10 cut_quantile_25 (94, 4)
     unique_donor cut_quantile_25 publicity10  size
2      1410**a16        low_freq     private     0
3      1410**a16        low_freq      public     0
10    1540A**a16        low_freq     private     0
11    1540A**a16        low_freq      public     0
22     1563**a16        low_freq     private     0
..           ...             ...         ...   ...
339     PK7**b55        low_freq      public     0
342     PK8**b55        low_freq     private     0
343     PK8**b55        low_freq      public     0
350    SA62**a16        low_freq     private     0
351    SA62**a16        low_freq      public     0

[94 rows x 4 columns]
-----------------------------------------------------
publicity10 cut_quantile_50 (2, 4)
    unique_donor cut_quantile_50 publicity10  size
11   1540A**a16        low_freq      public     0
75   H1601**a16        low_freq      public     0
-----------------------------------------------------
publicity10 cut_quantile_75 (1, 4)
    unique_donor cut_quantile_75 publicity10  size
73   H1601**a16       high_freq      public     0
-----------------------------------------------------
publicity10 cut_quantile_80 (1, 4)
    unique_donor cut_quantile_80 publicity10  size
73   H1601**a16       high_freq      public     0
-----------------------------------------------------
publicity10 cut_quantile_85 (2, 4)
    unique_donor cut_quantile_85 publicity10  size
1     1410**a16       high_freq      public     0
73   H1601**a16       high_freq      public     0
-----------------------------------------------------
publicity10 cut_quantile_90 (2, 4)
    unique_donor cut_quantile_90 publicity10  size
1     1410**a16       high_freq      public     0
73   H1601**a16       high_freq      public     0
-----------------------------------------------------

publicity10 cut_quantile_95 (3, 4)
    unique_donor cut_quantile_95 publicity10  size
1     1410**a16       high_freq      public     0
25    1564**a16       high_freq      public     0
73   H1601**a16       high_freq      public     0
-----------------------------------------------------
publicity20 cut_quantile_10 (177, 4)
     unique_donor cut_quantile_10 publicity20  size
2      1410**a16        low_freq     private     0
3      1410**a16        low_freq      public     0
6     1537B**a16        low_freq     private     0
7     1537B**a16        low_freq      public     0
10    1540A**a16        low_freq     private     0
..           ...             ...         ...   ...
347    SA61**a16        low_freq      public     0
350    SA62**a16        low_freq     private     0
351    SA62**a16        low_freq      public     0
354    SA71**a16        low_freq     private     0
355    SA71**a16        low_freq      public     0

[177 rows x 4 columns]
-----------------------------------------------------
publicity20 cut_quantile_15 (170, 4)
     unique_donor cut_quantile_15 publicity20  size
2      1410**a16        low_freq     private     0
3      1410**a16        low_freq      public     0
6     1537B**a16        low_freq     private     0
7     1537B**a16        low_freq      public     0
10    1540A**a16        low_freq     private     0
..           ...             ...         ...   ...
347    SA61**a16        low_freq      public     0
350    SA62**a16        low_freq     private     0
351    SA62**a16        low_freq      public     0
354    SA71**a16        low_freq     private     0
355    SA71**a16        low_freq      public     0

[170 rows x 4 columns]
-----------------------------------------------------
publicity20 cut_quantile_20 (144, 4)
     unique_donor cut_quantile_20 publicity20  size
2      1410**a16        low_freq     private     0
3      1410**a16        low_freq      public     0
7     1537B**a16        low_freq      public     0
10    1540A**a16        low_freq     private     0
11    1540A**a16        low_freq      public     0
..           ...             ...         ...   ...
347    SA61**a16        low_freq      public     0
350    SA62**a16        low_freq     private     0
351    SA62**a16        low_freq      public     0
354    SA71**a16        low_freq     private     0
355    SA71**a16        low_freq      public     0

[144 rows x 4 columns]
-----------------------------------------------------
publicity20 cut_quantile_25 (97, 4)
     unique_donor cut_quantile_25 publicity20  size
2      1410**a16        low_freq     private     0
3      1410**a16        low_freq      public     0
7     1537B**a16        low_freq      public     0
10    1540A**a16        low_freq     private     0
11    1540A**a16        low_freq      public     0
..           ...             ...         ...   ...
339     PK7**b55        low_freq      public     0
342     PK8**b55        low_freq     private     0
343     PK8**b55        low_freq      public     0
350    SA62**a16        low_freq     private     0
351    SA62**a16        low_freq      public     0

[97 rows x 4 columns]
-----------------------------------------------------
publicity20 cut_quantile_50 (4, 4)
    unique_donor cut_quantile_50 publicity20  size
3     1410**a16        low_freq      public     0
11   1540A**a16        low_freq      public     0
73   H1601**a16       high_freq      public     0
75   H1601**a16        low_freq      public     0
-----------------------------------------------------
publicity20 cut_quantile_75 (3, 4)
    unique_donor cut_quantile_75 publicity20  size
11   1540A**a16        low_freq      public     0
73   H1601**a16       high_freq      public     0
75   H1601**a16        low_freq      public     0
-----------------------------------------------------
publicity20 cut_quantile_80 (3, 4)
    unique_donor cut_quantile_80 publicity20  size
11   1540A**a16        low_freq      public     0
73   H1601**a16       high_freq      public     0
75   H1601**a16        low_freq      public     0
-----------------------------------------------------
publicity20 cut_quantile_85 (4, 4)
    unique_donor cut_quantile_85 publicity20  size
1     1410**a16       high_freq      public     0
11   1540A**a16        low_freq      public     0
73   H1601**a16       high_freq      public     0
75   H1601**a16        low_freq      public     0
-----------------------------------------------------
publicity20 cut_quantile_90 (4, 4)
    unique_donor cut_quantile_90 publicity20  size
1     1410**a16       high_freq      public     0
11   1540A**a16        low_freq      public     0
73   H1601**a16       high_freq      public     0
75   H1601**a16        low_freq      public     0
-----------------------------------------------------
publicity20 cut_quantile_95 (6, 4)
     unique_donor cut_quantile_95 publicity20  size
1      1410**a16       high_freq      public     0
11    1540A**a16        low_freq      public     0
25     1564**a16       high_freq      public     0
73    H1601**a16       high_freq      public     0
75    H1601**a16        low_freq      public     0
85  H1614A2**a16       high_freq      public     0
-----------------------------------------------------
publicity30 cut_quantile_10 (178, 4)
     unique_donor cut_quantile_10 publicity30  size
2      1410**a16        low_freq     private     0
3      1410**a16        low_freq      public     0
6     1537B**a16        low_freq     private     0
7     1537B**a16        low_freq      public     0
10    1540A**a16        low_freq     private     0
..           ...             ...         ...   ...
347    SA61**a16        low_freq      public     0
350    SA62**a16        low_freq     private     0
351    SA62**a16        low_freq      public     0
354    SA71**a16        low_freq     private     0
355    SA71**a16        low_freq      public     0

[178 rows x 4 columns]
-----------------------------------------------------
publicity30 cut_quantile_15 (170, 4)
     unique_donor cut_quantile_15 publicity30  size
2      1410**a16        low_freq     private     0
3      1410**a16        low_freq      public     0
6     1537B**a16        low_freq     private     0
7     1537B**a16        low_freq      public     0
10    1540A**a16        low_freq     private     0
..           ...             ...         ...   ...
347    SA61**a16        low_freq      public     0
350    SA62**a16        low_freq     private     0
351    SA62**a16        low_freq      public     0
354    SA71**a16        low_freq     private     0
355    SA71**a16        low_freq      public     0

[170 rows x 4 columns]
-----------------------------------------------------
publicity30 cut_quantile_20 (146, 4)
     unique_donor cut_quantile_20 publicity30  size
2      1410**a16        low_freq     private     0
3      1410**a16        low_freq      public     0
7     1537B**a16        low_freq      public     0
10    1540A**a16        low_freq     private     0
11    1540A**a16        low_freq      public     0
..           ...             ...         ...   ...
347    SA61**a16        low_freq      public     0
350    SA62**a16        low_freq     private     0
351    SA62**a16        low_freq      public     0
354    SA71**a16        low_freq     private     0
355    SA71**a16        low_freq      public     0

[146 rows x 4 columns]
-----------------------------------------------------
publicity30 cut_quantile_25 (100, 4)
     unique_donor cut_quantile_25 publicity30  size
2      1410**a16        low_freq     private     0
3      1410**a16        low_freq      public     0
7     1537B**a16        low_freq      public     0
10    1540A**a16        low_freq     private     0
11    1540A**a16        low_freq      public     0
..           ...             ...         ...   ...
339     PK7**b55        low_freq      public     0
342     PK8**b55        low_freq     private     0
343     PK8**b55        low_freq      public     0
350    SA62**a16        low_freq     private     0
351    SA62**a16        low_freq      public     0

[100 rows x 4 columns]
-----------------------------------------------------
publicity30 cut_quantile_50 (5, 4)
    unique_donor cut_quantile_50 publicity30  size
3     1410**a16        low_freq      public     0
11   1540A**a16        low_freq      public     0
15    1542**a16        low_freq      public     0
73   H1601**a16       high_freq      public     0
75   H1601**a16        low_freq      public     0
-----------------------------------------------------
publicity30 cut_quantile_75 (4, 4)
    unique_donor cut_quantile_75 publicity30  size
11   1540A**a16        low_freq      public     0
15    1542**a16        low_freq      public     0
73   H1601**a16       high_freq      public     0
75   H1601**a16        low_freq      public     0
-----------------------------------------------------

publicity30 cut_quantile_80 (4, 4)
    unique_donor cut_quantile_80 publicity30  size
11   1540A**a16        low_freq      public     0
15    1542**a16        low_freq      public     0
73   H1601**a16       high_freq      public     0
75   H1601**a16        low_freq      public     0
-----------------------------------------------------
publicity30 cut_quantile_85 (4, 4)
    unique_donor cut_quantile_85 publicity30  size
1     1410**a16       high_freq      public     0
11   1540A**a16        low_freq      public     0
73   H1601**a16       high_freq      public     0
75   H1601**a16        low_freq      public     0
-----------------------------------------------------
publicity30 cut_quantile_90 (4, 4)
    unique_donor cut_quantile_90 publicity30  size
1     1410**a16       high_freq      public     0
11   1540A**a16        low_freq      public     0
73   H1601**a16       high_freq      public     0
75   H1601**a16        low_freq      public     0
-----------------------------------------------------
publicity30 cut_quantile_95 (7, 4)
      unique_donor cut_quantile_95 publicity30  size
1       1410**a16       high_freq      public     0
11     1540A**a16        low_freq      public     0
25      1564**a16       high_freq      public     0
73     H1601**a16       high_freq      public     0
75     H1601**a16        low_freq      public     0
85   H1614A2**a16       high_freq      public     0
353     SA71**a16       high_freq      public     0
-----------------------------------------------------
publicity42 cut_quantile_10 (178, 4)
     unique_donor cut_quantile_10 publicity42  size
2      1410**a16        low_freq     private     0
3      1410**a16        low_freq      public     0
6     1537B**a16        low_freq     private     0
7     1537B**a16        low_freq      public     0
10    1540A**a16        low_freq     private     0
..           ...             ...         ...   ...
347    SA61**a16        low_freq      public     0
350    SA62**a16        low_freq     private     0
351    SA62**a16        low_freq      public     0
354    SA71**a16        low_freq     private     0
355    SA71**a16        low_freq      public     0

[178 rows x 4 columns]
-----------------------------------------------------
publicity42 cut_quantile_15 (170, 4)
     unique_donor cut_quantile_15 publicity42  size
2      1410**a16        low_freq     private     0
3      1410**a16        low_freq      public     0
6     1537B**a16        low_freq     private     0
7     1537B**a16        low_freq      public     0
10    1540A**a16        low_freq     private     0
..           ...             ...         ...   ...
347    SA61**a16        low_freq      public     0
350    SA62**a16        low_freq     private     0
351    SA62**a16        low_freq      public     0
354    SA71**a16        low_freq     private     0
355    SA71**a16        low_freq      public     0

[170 rows x 4 columns]
-----------------------------------------------------
publicity42 cut_quantile_20 (148, 4)
     unique_donor cut_quantile_20 publicity42  size
2      1410**a16        low_freq     private     0
3      1410**a16        low_freq      public     0
7     1537B**a16        low_freq      public     0
10    1540A**a16        low_freq     private     0
11    1540A**a16        low_freq      public     0
..           ...             ...         ...   ...
347    SA61**a16        low_freq      public     0
350    SA62**a16        low_freq     private     0
351    SA62**a16        low_freq      public     0
354    SA71**a16        low_freq     private     0
355    SA71**a16        low_freq      public     0

[148 rows x 4 columns]
-----------------------------------------------------
publicity42 cut_quantile_25 (102, 4)
     unique_donor cut_quantile_25 publicity42  size
2      1410**a16        low_freq     private     0
3      1410**a16        low_freq      public     0
7     1537B**a16        low_freq      public     0
10    1540A**a16        low_freq     private     0
11    1540A**a16        low_freq      public     0
..           ...             ...         ...   ...
339     PK7**b55        low_freq      public     0
342     PK8**b55        low_freq     private     0
343     PK8**b55        low_freq      public     0
350    SA62**a16        low_freq     private     0
351    SA62**a16        low_freq      public     0

[102 rows x 4 columns]
-----------------------------------------------------
publicity42 cut_quantile_50 (11, 4)
     unique_donor cut_quantile_50 publicity42  size
3      1410**a16        low_freq      public     0
11    1540A**a16        low_freq      public     0
15     1542**a16        low_freq      public     0
27     1564**a16        low_freq      public     0
73    H1601**a16       high_freq      public     0
75    H1601**a16        low_freq      public     0
159   LT781**b55        low_freq      public     0
227   PAX19**b55        low_freq      public     0
247    PK10**b55        low_freq      public     0
303    PK27**b55        low_freq      public     0
343     PK8**b55        low_freq      public     0
-----------------------------------------------------
publicity42 cut_quantile_75 (5, 4)
     unique_donor cut_quantile_75 publicity42  size
11    1540A**a16        low_freq      public     0
15     1542**a16        low_freq      public     0
73    H1601**a16       high_freq      public     0
75    H1601**a16        low_freq      public     0
227   PAX19**b55        low_freq      public     0
-----------------------------------------------------
publicity42 cut_quantile_80 (4, 4)
    unique_donor cut_quantile_80 publicity42  size
11   1540A**a16        low_freq      public     0
15    1542**a16        low_freq      public     0
73   H1601**a16       high_freq      public     0
75   H1601**a16        low_freq      public     0
-----------------------------------------------------
publicity42 cut_quantile_85 (4, 4)
    unique_donor cut_quantile_85 publicity42  size
1     1410**a16       high_freq      public     0
11   1540A**a16        low_freq      public     0
73   H1601**a16       high_freq      public     0
75   H1601**a16        low_freq      public     0
-----------------------------------------------------
publicity42 cut_quantile_90 (4, 4)
    unique_donor cut_quantile_90 publicity42  size
1     1410**a16       high_freq      public     0
11   1540A**a16        low_freq      public     0
73   H1601**a16       high_freq      public     0
75   H1601**a16        low_freq      public     0
-----------------------------------------------------
publicity42 cut_quantile_95 (7, 4)
      unique_donor cut_quantile_95 publicity42  size
1       1410**a16       high_freq      public     0
11     1540A**a16        low_freq      public     0
25      1564**a16       high_freq      public     0
73     H1601**a16       high_freq      public     0
75     H1601**a16        low_freq      public     0
85   H1614A2**a16       high_freq      public     0
353     SA71**a16       high_freq      public     0
-----------------------------------------------------

In [87]:
m5d_donoragg_aaTCRdist3 = m5d_donoragg_aa[['donor', 'pheno', 'dataset', 'donor_category', 'donor_category3',
                                                  'unique_donor', 'cdr3aa_translated', 'cdr3aa_string', 'aastring_length',
                                                   'txt', 'txt_first', 'txt_last', 'count_dis', 'count_sum', 'cdr3nt_dis',
                                                   'cdr3nt_first', 'cdr3nt_last', 'v_dis', 'v_first', 'v_last', 'd_dis',
                                                   'd_first', 'd_last', 'j_dis', 'j_first', 'j_last', 'count_in_difdonor',
                                                   'cdr3aa_publicity', 'publicity', 'publicity3c', 'publicity2', 'publicity3', 
                                                   'publicity5', 'publicity10', 'publicity20', 'publicity30', 'publicity42', 
                                                   'donor_sum', 'aa_freq', 'quantile_10', 'cut_quantile_10', 'quantile_15', 
                                                   'cut_quantile_15', 'quantile_20', 'cut_quantile_20',
                                                   'quantile_25', 'cut_quantile_25', 'quantile_50', 'cut_quantile_50', 
                                                   'quantile_75', 'cut_quantile_75', 'quantile_80', 'cut_quantile_80',
                                                   'quantile_85', 'cut_quantile_85', 'quantile_90', 'cut_quantile_90',
                                                   'quantile_95', 'cut_quantile_95', 'quantile_8', 'cut_quantile_8']].copy()
# rename the columns needed as the input for tcrdist3
# unique_donor: subject, count_sum: count, v_first: v_d_gene, d_first: d_d_gene, j_first: j_d_gene,
# cdr3aa_string: cdr3_d_aa,
m5d_donoragg_aaTCRdist3.columns = ['donor', 'pheno', 'dataset', 'donor_category', 'donor_category3',
                                   'subject', 'cdr3aa_translated', 'cdr3_d_aa', 'aa_length',
                                   'txt', 'txt_first', 'txt_last', 'count_dis', 'count', 'cdr3nt_dis',
                                   'cdr3nt_first', 'cdr3nt_last', 'v_dis', 'v_d_gene', 'v_last', 'd_dis',
                                   'd_d_gene', 'd_last', 'j_dis', 'j_d_gene', 'j_last', 'count_in_difdonor',
                                   'cdr3aa_publicity', 'publicity', 'publicity3c', 'publicity2', 'publicity3', 
                                   'publicity5', 'publicity10', 'publicity20', 'publicity30', 'publicity42', 
                                   'donor_sum', 'aa_freq', 'quantile_10', 'cut_quantile_10', 'quantile_15', 
                                   'cut_quantile_15', 'quantile_20', 'cut_quantile_20',
                                   'quantile_25', 'cut_quantile_25', 'quantile_50', 'cut_quantile_50', 
                                   'quantile_75', 'cut_quantile_75', 'quantile_80', 'cut_quantile_80',
                                   'quantile_85', 'cut_quantile_85', 'quantile_90', 'cut_quantile_90',
                                   'quantile_95', 'cut_quantile_95', 'quantile_8', 'cut_quantile_8']

In [88]:
m5d_donoragg_aaTCRdist3['v_d_gene'] = m5d_donoragg_aaTCRdist3['v_d_gene'].apply(
    lambda x: f"{x}*01")
m5d_donoragg_aaTCRdist3['j_d_gene'] = m5d_donoragg_aaTCRdist3['j_d_gene'].apply(
    lambda x: f"{x}*01")

m5d_donoragg_aaTCRdist3['vj_d_gene'] = m5d_donoragg_aaTCRdist3['v_d_gene'] + \
    '_' + m5d_donoragg_aaTCRdist3['j_d_gene']

print(m5d_donoragg_aaTCRdist3.shape)
m5d_donoragg_aaTCRdist3.to_csv('../data/output_data/m5d_donoragg_aaTCRdist3.csv', index=False)
# m5d_donoragg_aaTCRdist3.to_csv('/home/lihua/Rcode/TCRdist/m5d_donoragg_aaTCRdist3.csv', index=False)

(319355, 62)

In [89]:
m5d_donoragg_aaTCRdist3.columns

Index(['donor', 'pheno', 'dataset', 'donor_category', 'donor_category3',
       'subject', 'cdr3aa_translated', 'cdr3_d_aa', 'aa_length', 'txt',
       'txt_first', 'txt_last', 'count_dis', 'count', 'cdr3nt_dis',
       'cdr3nt_first', 'cdr3nt_last', 'v_dis', 'v_d_gene', 'v_last', 'd_dis',
       'd_d_gene', 'd_last', 'j_dis', 'j_d_gene', 'j_last',
       'count_in_difdonor', 'cdr3aa_publicity', 'publicity', 'publicity3c',
       'publicity2', 'publicity3', 'publicity5', 'publicity10', 'publicity20',
       'publicity30', 'publicity42', 'donor_sum', 'aa_freq', 'quantile_10',
       'cut_quantile_10', 'quantile_15', 'cut_quantile_15', 'quantile_20',
       'cut_quantile_20', 'quantile_25', 'cut_quantile_25', 'quantile_50',
       'cut_quantile_50', 'quantile_75', 'cut_quantile_75', 'quantile_80',
       'cut_quantile_80', 'quantile_85', 'cut_quantile_85', 'quantile_90',
       'cut_quantile_90', 'quantile_95', 'cut_quantile_95', 'quantile_8',
       'cut_quantile_8', 'vj_d_gene'],
      dtype='object')